// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$29 {

    static final FunctionDescriptor nc_get_var1_uint$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var1_uint$MH = RuntimeHelper.downcallHandle(
        "nc_get_var1_uint",
        constants$29.nc_get_var1_uint$FUNC
    );
    static final FunctionDescriptor nc_put_var1_longlong$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var1_longlong$MH = RuntimeHelper.downcallHandle(
        "nc_put_var1_longlong",
        constants$29.nc_put_var1_longlong$FUNC
    );
    static final FunctionDescriptor nc_get_var1_longlong$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var1_longlong$MH = RuntimeHelper.downcallHandle(
        "nc_get_var1_longlong",
        constants$29.nc_get_var1_longlong$FUNC
    );
    static final FunctionDescriptor nc_put_var1_ulonglong$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var1_ulonglong$MH = RuntimeHelper.downcallHandle(
        "nc_put_var1_ulonglong",
        constants$29.nc_put_var1_ulonglong$FUNC
    );
    static final FunctionDescriptor nc_get_var1_ulonglong$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var1_ulonglong$MH = RuntimeHelper.downcallHandle(
        "nc_get_var1_ulonglong",
        constants$29.nc_get_var1_ulonglong$FUNC
    );
    static final FunctionDescriptor nc_put_var1_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var1_string$MH = RuntimeHelper.downcallHandle(
        "nc_put_var1_string",
        constants$29.nc_put_var1_string$FUNC
    );
}


