// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$114 {

    static final FunctionDescriptor DFSDsetdims$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFSDsetdims$MH = RuntimeHelper.downcallHandle(
        "DFSDsetdims",
        constants$114.DFSDsetdims$FUNC
    );
    static final FunctionDescriptor DFSDsetdatastrs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFSDsetdatastrs$MH = RuntimeHelper.downcallHandle(
        "DFSDsetdatastrs",
        constants$114.DFSDsetdatastrs$FUNC
    );
    static final FunctionDescriptor DFSDsetdimstrs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFSDsetdimstrs$MH = RuntimeHelper.downcallHandle(
        "DFSDsetdimstrs",
        constants$114.DFSDsetdimstrs$FUNC
    );
    static final FunctionDescriptor DFSDsetdimscale$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFSDsetdimscale$MH = RuntimeHelper.downcallHandle(
        "DFSDsetdimscale",
        constants$114.DFSDsetdimscale$FUNC
    );
    static final FunctionDescriptor DFSDsetrange$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFSDsetrange$MH = RuntimeHelper.downcallHandle(
        "DFSDsetrange",
        constants$114.DFSDsetrange$FUNC
    );
    static final FunctionDescriptor DFSDputdata$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFSDputdata$MH = RuntimeHelper.downcallHandle(
        "DFSDputdata",
        constants$114.DFSDputdata$FUNC
    );
}


