// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$144 {

    static final FunctionDescriptor Vgisinternal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle Vgisinternal$MH = RuntimeHelper.downcallHandle(
        "Vgisinternal",
        constants$144.Vgisinternal$FUNC
    );
    static final FunctionDescriptor Visinternal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle Visinternal$MH = RuntimeHelper.downcallHandle(
        "Visinternal",
        constants$144.Visinternal$FUNC
    );
    static final FunctionDescriptor Vgetvgroups$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle Vgetvgroups$MH = RuntimeHelper.downcallHandle(
        "Vgetvgroups",
        constants$144.Vgetvgroups$FUNC
    );
    static final FunctionDescriptor Vdeletetagref$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle Vdeletetagref$MH = RuntimeHelper.downcallHandle(
        "Vdeletetagref",
        constants$144.Vdeletetagref$FUNC
    );
    static final FunctionDescriptor VPshutdown$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle VPshutdown$MH = RuntimeHelper.downcallHandle(
        "VPshutdown",
        constants$144.VPshutdown$FUNC
    );
    static final FunctionDescriptor scanattrs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle scanattrs$MH = RuntimeHelper.downcallHandle(
        "scanattrs",
        constants$144.scanattrs$FUNC
    );
}


