// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$154 {

    static final FunctionDescriptor sd_ncvardef$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sd_ncvardef$MH = RuntimeHelper.downcallHandle(
        "sd_ncvardef",
        constants$154.sd_ncvardef$FUNC
    );
    static final FunctionDescriptor sd_ncvarid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sd_ncvarid$MH = RuntimeHelper.downcallHandle(
        "sd_ncvarid",
        constants$154.sd_ncvarid$FUNC
    );
    static final FunctionDescriptor sd_ncvarinq$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sd_ncvarinq$MH = RuntimeHelper.downcallHandle(
        "sd_ncvarinq",
        constants$154.sd_ncvarinq$FUNC
    );
    static final FunctionDescriptor sd_ncvarput1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sd_ncvarput1$MH = RuntimeHelper.downcallHandle(
        "sd_ncvarput1",
        constants$154.sd_ncvarput1$FUNC
    );
    static final FunctionDescriptor sd_ncvarget1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sd_ncvarget1$MH = RuntimeHelper.downcallHandle(
        "sd_ncvarget1",
        constants$154.sd_ncvarget1$FUNC
    );
    static final FunctionDescriptor sd_ncvarput$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sd_ncvarput$MH = RuntimeHelper.downcallHandle(
        "sd_ncvarput",
        constants$154.sd_ncvarput$FUNC
    );
}


