// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$203 {

    static final MemorySegment _HDF_Remarks$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("remarks");
    static final MemorySegment _HDF_AnnoLabel$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("anno_label");
}


