// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$124 {

    static final FunctionDescriptor rigcompare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle rigcompare$MH = RuntimeHelper.downcallHandle(
        "rigcompare",
        constants$124.rigcompare$FUNC
    );
    static final FunctionDescriptor GRstart$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle GRstart$MH = RuntimeHelper.downcallHandle(
        "GRstart",
        constants$124.GRstart$FUNC
    );
    static final FunctionDescriptor GRfileinfo$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GRfileinfo$MH = RuntimeHelper.downcallHandle(
        "GRfileinfo",
        constants$124.GRfileinfo$FUNC
    );
    static final FunctionDescriptor GRend$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle GRend$MH = RuntimeHelper.downcallHandle(
        "GRend",
        constants$124.GRend$FUNC
    );
    static final FunctionDescriptor GRcreate$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GRcreate$MH = RuntimeHelper.downcallHandle(
        "GRcreate",
        constants$124.GRcreate$FUNC
    );
    static final FunctionDescriptor GRselect$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle GRselect$MH = RuntimeHelper.downcallHandle(
        "GRselect",
        constants$124.GRselect$FUNC
    );
}


