// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.foreign.*;

class constants$201 {

    static final MemorySegment _HDF_LongName$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("long_name");
    static final MemorySegment _HDF_Units$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("units");
    static final MemorySegment _HDF_Format$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("format");
    static final MemorySegment _HDF_CoordSys$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("coordsys");
    static final MemorySegment _HDF_ValidRange$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("valid_range");
    static final MemorySegment _HDF_ScaleFactor$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("scale_factor");
}


