// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$139 {

    static final FunctionDescriptor Vfinish$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle Vfinish$MH = RuntimeHelper.downcallHandle(
        "Vfinish",
        constants$139.Vfinish$FUNC
    );
    static final FunctionDescriptor Vopen$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle Vopen$MH = RuntimeHelper.downcallHandle(
        "Vopen",
        constants$139.Vopen$FUNC
    );
    static final FunctionDescriptor Vclose$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle Vclose$MH = RuntimeHelper.downcallHandle(
        "Vclose",
        constants$139.Vclose$FUNC
    );
    static final FunctionDescriptor vexistvg$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle vexistvg$MH = RuntimeHelper.downcallHandle(
        "vexistvg",
        constants$139.vexistvg$FUNC
    );
    static final FunctionDescriptor Vattach$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle Vattach$MH = RuntimeHelper.downcallHandle(
        "Vattach",
        constants$139.Vattach$FUNC
    );
    static final FunctionDescriptor Vdetach$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle Vdetach$MH = RuntimeHelper.downcallHandle(
        "Vdetach",
        constants$139.Vdetach$FUNC
    );
}


