// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$125 {

    static final FunctionDescriptor GRnametoindex$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GRnametoindex$MH = RuntimeHelper.downcallHandle(
        "GRnametoindex",
        constants$125.GRnametoindex$FUNC
    );
    static final FunctionDescriptor GRgetiminfo$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GRgetiminfo$MH = RuntimeHelper.downcallHandle(
        "GRgetiminfo",
        constants$125.GRgetiminfo$FUNC
    );
    static final FunctionDescriptor GRgetnluts$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle GRgetnluts$MH = RuntimeHelper.downcallHandle(
        "GRgetnluts",
        constants$125.GRgetnluts$FUNC
    );
    static final FunctionDescriptor GRwriteimage$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GRwriteimage$MH = RuntimeHelper.downcallHandle(
        "GRwriteimage",
        constants$125.GRwriteimage$FUNC
    );
    static final FunctionDescriptor GRreadimage$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GRreadimage$MH = RuntimeHelper.downcallHandle(
        "GRreadimage",
        constants$125.GRreadimage$FUNC
    );
    static final FunctionDescriptor GRendaccess$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle GRendaccess$MH = RuntimeHelper.downcallHandle(
        "GRendaccess",
        constants$125.GRendaccess$FUNC
    );
}


