// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$160 {

    static final FunctionDescriptor SDnametoindices$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SDnametoindices$MH = RuntimeHelper.downcallHandle(
        "SDnametoindices",
        constants$160.SDnametoindices$FUNC
    );
    static final FunctionDescriptor SDgetnumvars_byname$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SDgetnumvars_byname$MH = RuntimeHelper.downcallHandle(
        "SDgetnumvars_byname",
        constants$160.SDgetnumvars_byname$FUNC
    );
    static final FunctionDescriptor SDgetrange$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SDgetrange$MH = RuntimeHelper.downcallHandle(
        "SDgetrange",
        constants$160.SDgetrange$FUNC
    );
    static final FunctionDescriptor SDcreate$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SDcreate$MH = RuntimeHelper.downcallHandle(
        "SDcreate",
        constants$160.SDcreate$FUNC
    );
    static final FunctionDescriptor SDgetdimid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle SDgetdimid$MH = RuntimeHelper.downcallHandle(
        "SDgetdimid",
        constants$160.SDgetdimid$FUNC
    );
    static final FunctionDescriptor SDsetdimname$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SDsetdimname$MH = RuntimeHelper.downcallHandle(
        "SDsetdimname",
        constants$160.SDsetdimname$FUNC
    );
}


