// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$95 {

    static final FunctionDescriptor Hbitappendable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle Hbitappendable$MH = RuntimeHelper.downcallHandle(
        "Hbitappendable",
        constants$95.Hbitappendable$FUNC
    );
    static final FunctionDescriptor Hbitwrite$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle Hbitwrite$MH = RuntimeHelper.downcallHandle(
        "Hbitwrite",
        constants$95.Hbitwrite$FUNC
    );
    static final FunctionDescriptor Hbitread$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle Hbitread$MH = RuntimeHelper.downcallHandle(
        "Hbitread",
        constants$95.Hbitread$FUNC
    );
    static final FunctionDescriptor Hbitseek$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle Hbitseek$MH = RuntimeHelper.downcallHandle(
        "Hbitseek",
        constants$95.Hbitseek$FUNC
    );
    static final FunctionDescriptor Hgetbit$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle Hgetbit$MH = RuntimeHelper.downcallHandle(
        "Hgetbit",
        constants$95.Hgetbit$FUNC
    );
    static final FunctionDescriptor Hendbitaccess$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle Hendbitaccess$MH = RuntimeHelper.downcallHandle(
        "Hendbitaccess",
        constants$95.Hendbitaccess$FUNC
    );
}


