// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$83 {

    static final FunctionDescriptor HDputc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle HDputc$MH = RuntimeHelper.downcallHandle(
        "HDputc",
        constants$83.HDputc$FUNC
    );
    static final FunctionDescriptor Hgetelement$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle Hgetelement$MH = RuntimeHelper.downcallHandle(
        "Hgetelement",
        constants$83.Hgetelement$FUNC
    );
    static final FunctionDescriptor Hputelement$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle Hputelement$MH = RuntimeHelper.downcallHandle(
        "Hputelement",
        constants$83.Hputelement$FUNC
    );
    static final FunctionDescriptor Hlength$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle Hlength$MH = RuntimeHelper.downcallHandle(
        "Hlength",
        constants$83.Hlength$FUNC
    );
    static final FunctionDescriptor Hoffset$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle Hoffset$MH = RuntimeHelper.downcallHandle(
        "Hoffset",
        constants$83.Hoffset$FUNC
    );
    static final FunctionDescriptor Hsync$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle Hsync$MH = RuntimeHelper.downcallHandle(
        "Hsync",
        constants$83.Hsync$FUNC
    );
}


