// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$121 {

    static final FunctionDescriptor DFKsb8b$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle DFKsb8b$MH = RuntimeHelper.downcallHandle(
        "DFKsb8b",
        constants$121.DFKsb8b$FUNC
    );
    static final FunctionDescriptor ANstart$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle ANstart$MH = RuntimeHelper.downcallHandle(
        "ANstart",
        constants$121.ANstart$FUNC
    );
    static final FunctionDescriptor ANfileinfo$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ANfileinfo$MH = RuntimeHelper.downcallHandle(
        "ANfileinfo",
        constants$121.ANfileinfo$FUNC
    );
    static final FunctionDescriptor ANend$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle ANend$MH = RuntimeHelper.downcallHandle(
        "ANend",
        constants$121.ANend$FUNC
    );
    static final FunctionDescriptor ANcreate$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle ANcreate$MH = RuntimeHelper.downcallHandle(
        "ANcreate",
        constants$121.ANcreate$FUNC
    );
    static final FunctionDescriptor ANcreatef$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle ANcreatef$MH = RuntimeHelper.downcallHandle(
        "ANcreatef",
        constants$121.ANcreatef$FUNC
    );
}


