// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$102 {

    static final FunctionDescriptor DFR8getpalref$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFR8getpalref$MH = RuntimeHelper.downcallHandle(
        "DFR8getpalref",
        constants$102.DFR8getpalref$FUNC
    );
    static final FunctionDescriptor DFR8Pshutdown$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle DFR8Pshutdown$MH = RuntimeHelper.downcallHandle(
        "DFR8Pshutdown",
        constants$102.DFR8Pshutdown$FUNC
    );
    static final FunctionDescriptor DFGRgetlutdims$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFGRgetlutdims$MH = RuntimeHelper.downcallHandle(
        "DFGRgetlutdims",
        constants$102.DFGRgetlutdims$FUNC
    );
    static final FunctionDescriptor DFGRreqlutil$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle DFGRreqlutil$MH = RuntimeHelper.downcallHandle(
        "DFGRreqlutil",
        constants$102.DFGRreqlutil$FUNC
    );
    static final FunctionDescriptor DFGRgetlut$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle DFGRgetlut$MH = RuntimeHelper.downcallHandle(
        "DFGRgetlut",
        constants$102.DFGRgetlut$FUNC
    );
    static final FunctionDescriptor DFGRgetimdims$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFGRgetimdims$MH = RuntimeHelper.downcallHandle(
        "DFGRgetimdims",
        constants$102.DFGRgetimdims$FUNC
    );
}


