// Generated by jextract

package sunya.cdm.netcdf.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$23 {

    static final FunctionDescriptor nc_get_att_ushort$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_att_ushort$MH = RuntimeHelper.downcallHandle(
        "nc_get_att_ushort",
        constants$23.nc_get_att_ushort$FUNC
    );
    static final FunctionDescriptor nc_put_att_uint$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_att_uint$MH = RuntimeHelper.downcallHandle(
        "nc_put_att_uint",
        constants$23.nc_put_att_uint$FUNC
    );
    static final FunctionDescriptor nc_get_att_uint$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_att_uint$MH = RuntimeHelper.downcallHandle(
        "nc_get_att_uint",
        constants$23.nc_get_att_uint$FUNC
    );
    static final FunctionDescriptor nc_put_att_longlong$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_att_longlong$MH = RuntimeHelper.downcallHandle(
        "nc_put_att_longlong",
        constants$23.nc_put_att_longlong$FUNC
    );
    static final FunctionDescriptor nc_get_att_longlong$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_att_longlong$MH = RuntimeHelper.downcallHandle(
        "nc_get_att_longlong",
        constants$23.nc_get_att_longlong$FUNC
    );
    static final FunctionDescriptor nc_put_att_ulonglong$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_att_ulonglong$MH = RuntimeHelper.downcallHandle(
        "nc_put_att_ulonglong",
        constants$23.nc_put_att_ulonglong$FUNC
    );
}


