// Generated by jextract

package sunya.cdm.netcdf.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$44 {

    static final FunctionDescriptor nc_get_var_schar$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var_schar$MH = RuntimeHelper.downcallHandle(
        "nc_get_var_schar",
        constants$44.nc_get_var_schar$FUNC
    );
    static final FunctionDescriptor nc_put_var_short$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var_short$MH = RuntimeHelper.downcallHandle(
        "nc_put_var_short",
        constants$44.nc_put_var_short$FUNC
    );
    static final FunctionDescriptor nc_get_var_short$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var_short$MH = RuntimeHelper.downcallHandle(
        "nc_get_var_short",
        constants$44.nc_get_var_short$FUNC
    );
    static final FunctionDescriptor nc_put_var_int$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var_int$MH = RuntimeHelper.downcallHandle(
        "nc_put_var_int",
        constants$44.nc_put_var_int$FUNC
    );
    static final FunctionDescriptor nc_get_var_int$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var_int$MH = RuntimeHelper.downcallHandle(
        "nc_get_var_int",
        constants$44.nc_get_var_int$FUNC
    );
    static final FunctionDescriptor nc_put_var_long$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var_long$MH = RuntimeHelper.downcallHandle(
        "nc_put_var_long",
        constants$44.nc_put_var_long$FUNC
    );
}


