// Generated by jextract

package sunya.cdm.netcdf.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$49 {

    static final FunctionDescriptor nc_put_vara_ubyte$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_vara_ubyte$MH = RuntimeHelper.downcallHandle(
        "nc_put_vara_ubyte",
        constants$49.nc_put_vara_ubyte$FUNC
    );
    static final FunctionDescriptor nc_get_vara_ubyte$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_vara_ubyte$MH = RuntimeHelper.downcallHandle(
        "nc_get_vara_ubyte",
        constants$49.nc_get_vara_ubyte$FUNC
    );
    static final FunctionDescriptor nc_put_vars_ubyte$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_vars_ubyte$MH = RuntimeHelper.downcallHandle(
        "nc_put_vars_ubyte",
        constants$49.nc_put_vars_ubyte$FUNC
    );
    static final FunctionDescriptor nc_get_vars_ubyte$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_vars_ubyte$MH = RuntimeHelper.downcallHandle(
        "nc_get_vars_ubyte",
        constants$49.nc_get_vars_ubyte$FUNC
    );
    static final FunctionDescriptor nc_put_varm_ubyte$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_varm_ubyte$MH = RuntimeHelper.downcallHandle(
        "nc_put_varm_ubyte",
        constants$49.nc_put_varm_ubyte$FUNC
    );
    static final FunctionDescriptor nc_get_varm_ubyte$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_varm_ubyte$MH = RuntimeHelper.downcallHandle(
        "nc_get_varm_ubyte",
        constants$49.nc_get_varm_ubyte$FUNC
    );
}


