// Generated by jextract

package com.sunya.netchdf.netcdf.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$10 {

    static final FunctionDescriptor nc_get_var$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var$MH = RuntimeHelper.downcallHandle(
        "nc_get_var",
        constants$10.nc_get_var$FUNC
    );
    static final FunctionDescriptor nc_put_var1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var1$MH = RuntimeHelper.downcallHandle(
        "nc_put_var1",
        constants$10.nc_put_var1$FUNC
    );
    static final FunctionDescriptor nc_get_var1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var1$MH = RuntimeHelper.downcallHandle(
        "nc_get_var1",
        constants$10.nc_get_var1$FUNC
    );
    static final FunctionDescriptor nc_put_vara$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_vara$MH = RuntimeHelper.downcallHandle(
        "nc_put_vara",
        constants$10.nc_put_vara$FUNC
    );
    static final FunctionDescriptor nc_get_vara$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_vara$MH = RuntimeHelper.downcallHandle(
        "nc_get_vara",
        constants$10.nc_get_vara$FUNC
    );
    static final FunctionDescriptor nc_put_vars$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_vars$MH = RuntimeHelper.downcallHandle(
        "nc_put_vars",
        constants$10.nc_put_vars$FUNC
    );
}


