// Generated by jextract

package com.sunya.netchdf.netcdf.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$27 {

    static final FunctionDescriptor nc_get_var1_short$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var1_short$MH = RuntimeHelper.downcallHandle(
        "nc_get_var1_short",
        constants$27.nc_get_var1_short$FUNC
    );
    static final FunctionDescriptor nc_put_var1_int$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var1_int$MH = RuntimeHelper.downcallHandle(
        "nc_put_var1_int",
        constants$27.nc_put_var1_int$FUNC
    );
    static final FunctionDescriptor nc_get_var1_int$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var1_int$MH = RuntimeHelper.downcallHandle(
        "nc_get_var1_int",
        constants$27.nc_get_var1_int$FUNC
    );
    static final FunctionDescriptor nc_put_var1_long$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var1_long$MH = RuntimeHelper.downcallHandle(
        "nc_put_var1_long",
        constants$27.nc_put_var1_long$FUNC
    );
    static final FunctionDescriptor nc_get_var1_long$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var1_long$MH = RuntimeHelper.downcallHandle(
        "nc_get_var1_long",
        constants$27.nc_get_var1_long$FUNC
    );
    static final FunctionDescriptor nc_put_var1_float$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var1_float$MH = RuntimeHelper.downcallHandle(
        "nc_put_var1_float",
        constants$27.nc_put_var1_float$FUNC
    );
}


