// Generated by jextract

package com.sunya.netchdf.netcdf.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$4 {

    static final FunctionDescriptor nc_def_grp$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_def_grp$MH = RuntimeHelper.downcallHandle(
        "nc_def_grp",
        constants$4.nc_def_grp$FUNC
    );
    static final FunctionDescriptor nc_rename_grp$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_rename_grp$MH = RuntimeHelper.downcallHandle(
        "nc_rename_grp",
        constants$4.nc_rename_grp$FUNC
    );
    static final FunctionDescriptor nc_def_compound$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_def_compound$MH = RuntimeHelper.downcallHandle(
        "nc_def_compound",
        constants$4.nc_def_compound$FUNC
    );
    static final FunctionDescriptor nc_insert_compound$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle nc_insert_compound$MH = RuntimeHelper.downcallHandle(
        "nc_insert_compound",
        constants$4.nc_insert_compound$FUNC
    );
    static final FunctionDescriptor nc_insert_array_compound$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_insert_array_compound$MH = RuntimeHelper.downcallHandle(
        "nc_insert_array_compound",
        constants$4.nc_insert_array_compound$FUNC
    );
    static final FunctionDescriptor nc_inq_type$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_type$MH = RuntimeHelper.downcallHandle(
        "nc_inq_type",
        constants$4.nc_inq_type$FUNC
    );
}


