// Generated by jextract

package com.sunya.netchdf.netcdf.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$22 {

    static final FunctionDescriptor nc_get_att_long$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_att_long$MH = RuntimeHelper.downcallHandle(
        "nc_get_att_long",
        constants$22.nc_get_att_long$FUNC
    );
    static final FunctionDescriptor nc_put_att_float$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_att_float$MH = RuntimeHelper.downcallHandle(
        "nc_put_att_float",
        constants$22.nc_put_att_float$FUNC
    );
    static final FunctionDescriptor nc_get_att_float$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_att_float$MH = RuntimeHelper.downcallHandle(
        "nc_get_att_float",
        constants$22.nc_get_att_float$FUNC
    );
    static final FunctionDescriptor nc_put_att_double$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_att_double$MH = RuntimeHelper.downcallHandle(
        "nc_put_att_double",
        constants$22.nc_put_att_double$FUNC
    );
    static final FunctionDescriptor nc_get_att_double$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_att_double$MH = RuntimeHelper.downcallHandle(
        "nc_get_att_double",
        constants$22.nc_get_att_double$FUNC
    );
    static final FunctionDescriptor nc_put_att_ushort$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_att_ushort$MH = RuntimeHelper.downcallHandle(
        "nc_put_att_ushort",
        constants$22.nc_put_att_ushort$FUNC
    );
}


