// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$155 {

    static final FunctionDescriptor sd_ncvarget$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sd_ncvarget$MH = RuntimeHelper.downcallHandle(
        "sd_ncvarget",
        constants$155.sd_ncvarget$FUNC
    );
    static final FunctionDescriptor sd_ncvarputs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sd_ncvarputs$MH = RuntimeHelper.downcallHandle(
        "sd_ncvarputs",
        constants$155.sd_ncvarputs$FUNC
    );
    static final FunctionDescriptor sd_ncvargets$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sd_ncvargets$MH = RuntimeHelper.downcallHandle(
        "sd_ncvargets",
        constants$155.sd_ncvargets$FUNC
    );
    static final FunctionDescriptor sd_ncvarputg$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sd_ncvarputg$MH = RuntimeHelper.downcallHandle(
        "sd_ncvarputg",
        constants$155.sd_ncvarputg$FUNC
    );
    static final FunctionDescriptor sd_ncvargetg$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sd_ncvargetg$MH = RuntimeHelper.downcallHandle(
        "sd_ncvargetg",
        constants$155.sd_ncvargetg$FUNC
    );
    static final FunctionDescriptor sd_ncvarrename$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sd_ncvarrename$MH = RuntimeHelper.downcallHandle(
        "sd_ncvarrename",
        constants$155.sd_ncvarrename$FUNC
    );
}


