// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$87 {

    static final FunctionDescriptor HPend$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle HPend$MH = RuntimeHelper.downcallHandle(
        "HPend",
        constants$87.HPend$FUNC
    );
    static final FunctionDescriptor HDdont_atexit$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle HDdont_atexit$MH = RuntimeHelper.downcallHandle(
        "HDdont_atexit",
        constants$87.HDdont_atexit$FUNC
    );
    static final FunctionDescriptor Hdupdd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle Hdupdd$MH = RuntimeHelper.downcallHandle(
        "Hdupdd",
        constants$87.Hdupdd$FUNC
    );
    static final FunctionDescriptor Hnumber$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle Hnumber$MH = RuntimeHelper.downcallHandle(
        "Hnumber",
        constants$87.Hnumber$FUNC
    );
    static final FunctionDescriptor Hnewref$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle Hnewref$MH = RuntimeHelper.downcallHandle(
        "Hnewref",
        constants$87.Hnewref$FUNC
    );
    static final FunctionDescriptor Htagnewref$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle Htagnewref$MH = RuntimeHelper.downcallHandle(
        "Htagnewref",
        constants$87.Htagnewref$FUNC
    );
}


