// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$200 {

    static final MemorySegment _HDF_CDF$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("CDF0.0");
    static final MemorySegment DATA0$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("Data0.0");
    static final MemorySegment ATTR_FIELD_NAME$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("VALUES");
    static final MemorySegment _HDF_CHK_TBL_CLASS$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("_HDF_CHK_TBL_");
    static final MemorySegment FILL_ATTR$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("FillValue");
    static final MemorySegment _FillValue$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("_FillValue");
}


