// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$117 {

    static final FunctionDescriptor DFSDgetNT$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFSDgetNT$MH = RuntimeHelper.downcallHandle(
        "DFSDgetNT",
        constants$117.DFSDgetNT$FUNC
    );
    static final FunctionDescriptor DFSDpre32sdg$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFSDpre32sdg$MH = RuntimeHelper.downcallHandle(
        "DFSDpre32sdg",
        constants$117.DFSDpre32sdg$FUNC
    );
    static final FunctionDescriptor DFSDsetcal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle DFSDsetcal$MH = RuntimeHelper.downcallHandle(
        "DFSDsetcal",
        constants$117.DFSDsetcal$FUNC
    );
    static final FunctionDescriptor DFSDgetcal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFSDgetcal$MH = RuntimeHelper.downcallHandle(
        "DFSDgetcal",
        constants$117.DFSDgetcal$FUNC
    );
    static final FunctionDescriptor DFSDwriteref$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle DFSDwriteref$MH = RuntimeHelper.downcallHandle(
        "DFSDwriteref",
        constants$117.DFSDwriteref$FUNC
    );
    static final FunctionDescriptor DFSDsetfillvalue$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFSDsetfillvalue$MH = RuntimeHelper.downcallHandle(
        "DFSDsetfillvalue",
        constants$117.DFSDsetfillvalue$FUNC
    );
}


