// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$135 {

    static final FunctionDescriptor VSdump$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle VSdump$MH = RuntimeHelper.downcallHandle(
        "VSdump",
        constants$135.VSdump$FUNC
    );
    static final FunctionDescriptor VSsetname$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VSsetname$MH = RuntimeHelper.downcallHandle(
        "VSsetname",
        constants$135.VSsetname$FUNC
    );
    static final FunctionDescriptor VSsetclass$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VSsetclass$MH = RuntimeHelper.downcallHandle(
        "VSsetclass",
        constants$135.VSsetclass$FUNC
    );
    static final FunctionDescriptor VSgetname$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VSgetname$MH = RuntimeHelper.downcallHandle(
        "VSgetname",
        constants$135.VSgetname$FUNC
    );
    static final FunctionDescriptor VSgetclass$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VSgetclass$MH = RuntimeHelper.downcallHandle(
        "VSgetclass",
        constants$135.VSgetclass$FUNC
    );
    static final FunctionDescriptor VSinquire$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VSinquire$MH = RuntimeHelper.downcallHandle(
        "VSinquire",
        constants$135.VSinquire$FUNC
    );
}


