// Generated by jextract

package com.sunya.netchdf.mfhdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$112 {

    static final FunctionDescriptor DFANIgetfannlen$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle DFANIgetfannlen$MH = RuntimeHelper.downcallHandle(
        "DFANIgetfannlen",
        constants$112.DFANIgetfannlen$FUNC
    );
    static final FunctionDescriptor DFANIgetfann$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle DFANIgetfann$MH = RuntimeHelper.downcallHandle(
        "DFANIgetfann",
        constants$112.DFANIgetfann$FUNC
    );
    static final FunctionDescriptor DFANPshutdown$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle DFANPshutdown$MH = RuntimeHelper.downcallHandle(
        "DFANPshutdown",
        constants$112.DFANPshutdown$FUNC
    );
    static final FunctionDescriptor DFSDgetdims$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle DFSDgetdims$MH = RuntimeHelper.downcallHandle(
        "DFSDgetdims",
        constants$112.DFSDgetdims$FUNC
    );
    static final FunctionDescriptor DFSDgetdatastrs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFSDgetdatastrs$MH = RuntimeHelper.downcallHandle(
        "DFSDgetdatastrs",
        constants$112.DFSDgetdatastrs$FUNC
    );
    static final FunctionDescriptor DFSDgetdimstrs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DFSDgetdimstrs$MH = RuntimeHelper.downcallHandle(
        "DFSDgetdimstrs",
        constants$112.DFSDgetdimstrs$FUNC
    );
}


