// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$3 {

    static final FunctionDescriptor nc_inq_grp_ncid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_grp_ncid$MH = RuntimeHelper.downcallHandle(
        "nc_inq_grp_ncid",
        constants$3.nc_inq_grp_ncid$FUNC
    );
    static final FunctionDescriptor nc_inq_grp_full_ncid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_grp_full_ncid$MH = RuntimeHelper.downcallHandle(
        "nc_inq_grp_full_ncid",
        constants$3.nc_inq_grp_full_ncid$FUNC
    );
    static final FunctionDescriptor nc_inq_varids$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_varids$MH = RuntimeHelper.downcallHandle(
        "nc_inq_varids",
        constants$3.nc_inq_varids$FUNC
    );
    static final FunctionDescriptor nc_inq_dimids$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle nc_inq_dimids$MH = RuntimeHelper.downcallHandle(
        "nc_inq_dimids",
        constants$3.nc_inq_dimids$FUNC
    );
    static final FunctionDescriptor nc_inq_typeids$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_typeids$MH = RuntimeHelper.downcallHandle(
        "nc_inq_typeids",
        constants$3.nc_inq_typeids$FUNC
    );
    static final FunctionDescriptor nc_inq_type_equal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_type_equal$MH = RuntimeHelper.downcallHandle(
        "nc_inq_type_equal",
        constants$3.nc_inq_type_equal$FUNC
    );
}


