// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$42 {

    static final FunctionDescriptor nc_get_varm_ulonglong$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_varm_ulonglong$MH = RuntimeHelper.downcallHandle(
        "nc_get_varm_ulonglong",
        constants$42.nc_get_varm_ulonglong$FUNC
    );
    static final FunctionDescriptor nc_put_varm_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_varm_string$MH = RuntimeHelper.downcallHandle(
        "nc_put_varm_string",
        constants$42.nc_put_varm_string$FUNC
    );
    static final FunctionDescriptor nc_get_varm_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_varm_string$MH = RuntimeHelper.downcallHandle(
        "nc_get_varm_string",
        constants$42.nc_get_varm_string$FUNC
    );
    static final FunctionDescriptor nc_put_var_text$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var_text$MH = RuntimeHelper.downcallHandle(
        "nc_put_var_text",
        constants$42.nc_put_var_text$FUNC
    );
    static final FunctionDescriptor nc_get_var_text$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var_text$MH = RuntimeHelper.downcallHandle(
        "nc_get_var_text",
        constants$42.nc_get_var_text$FUNC
    );
    static final FunctionDescriptor nc_put_var_uchar$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var_uchar$MH = RuntimeHelper.downcallHandle(
        "nc_put_var_uchar",
        constants$42.nc_put_var_uchar$FUNC
    );
}


