// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$48 {

    static final FunctionDescriptor nc_get_vars_ubyte$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_vars_ubyte$MH = RuntimeHelper.downcallHandle(
        "nc_get_vars_ubyte",
        constants$48.nc_get_vars_ubyte$FUNC
    );
    static final FunctionDescriptor nc_put_varm_ubyte$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_varm_ubyte$MH = RuntimeHelper.downcallHandle(
        "nc_put_varm_ubyte",
        constants$48.nc_put_varm_ubyte$FUNC
    );
    static final FunctionDescriptor nc_get_varm_ubyte$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_varm_ubyte$MH = RuntimeHelper.downcallHandle(
        "nc_get_varm_ubyte",
        constants$48.nc_get_varm_ubyte$FUNC
    );
    static final FunctionDescriptor nc_put_var_ubyte$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var_ubyte$MH = RuntimeHelper.downcallHandle(
        "nc_put_var_ubyte",
        constants$48.nc_put_var_ubyte$FUNC
    );
    static final FunctionDescriptor nc_get_var_ubyte$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var_ubyte$MH = RuntimeHelper.downcallHandle(
        "nc_get_var_ubyte",
        constants$48.nc_get_var_ubyte$FUNC
    );
    static final FunctionDescriptor nc_set_log_level$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle nc_set_log_level$MH = RuntimeHelper.downcallHandle(
        "nc_set_log_level",
        constants$48.nc_set_log_level$FUNC
    );
}


