// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$18 {

    static final FunctionDescriptor nc_inq_attid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_attid$MH = RuntimeHelper.downcallHandle(
        "nc_inq_attid",
        constants$18.nc_inq_attid$FUNC
    );
    static final FunctionDescriptor nc_inq_atttype$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_atttype$MH = RuntimeHelper.downcallHandle(
        "nc_inq_atttype",
        constants$18.nc_inq_atttype$FUNC
    );
    static final FunctionDescriptor nc_inq_attlen$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_attlen$MH = RuntimeHelper.downcallHandle(
        "nc_inq_attlen",
        constants$18.nc_inq_attlen$FUNC
    );
    static final FunctionDescriptor nc_inq_attname$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_attname$MH = RuntimeHelper.downcallHandle(
        "nc_inq_attname",
        constants$18.nc_inq_attname$FUNC
    );
    static final FunctionDescriptor nc_copy_att$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle nc_copy_att$MH = RuntimeHelper.downcallHandle(
        "nc_copy_att",
        constants$18.nc_copy_att$FUNC
    );
    static final FunctionDescriptor nc_rename_att$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_rename_att$MH = RuntimeHelper.downcallHandle(
        "nc_rename_att",
        constants$18.nc_rename_att$FUNC
    );
}


