// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$1 {

    static final FunctionDescriptor nc_create$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_create$MH = RuntimeHelper.downcallHandle(
        "nc_create",
        constants$1.nc_create$FUNC
    );
    static final FunctionDescriptor nc__open$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc__open$MH = RuntimeHelper.downcallHandle(
        "nc__open",
        constants$1.nc__open$FUNC
    );
    static final FunctionDescriptor nc_open$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_open$MH = RuntimeHelper.downcallHandle(
        "nc_open",
        constants$1.nc_open$FUNC
    );
    static final FunctionDescriptor nc_inq_path$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_path$MH = RuntimeHelper.downcallHandle(
        "nc_inq_path",
        constants$1.nc_inq_path$FUNC
    );
    static final FunctionDescriptor nc_inq_ncid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_ncid$MH = RuntimeHelper.downcallHandle(
        "nc_inq_ncid",
        constants$1.nc_inq_ncid$FUNC
    );
    static final FunctionDescriptor nc_inq_grps$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_grps$MH = RuntimeHelper.downcallHandle(
        "nc_inq_grps",
        constants$1.nc_inq_grps$FUNC
    );
}


