// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$28 {

    static final FunctionDescriptor nc_get_var1_ushort$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var1_ushort$MH = RuntimeHelper.downcallHandle(
        "nc_get_var1_ushort",
        constants$28.nc_get_var1_ushort$FUNC
    );
    static final FunctionDescriptor nc_put_var1_uint$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var1_uint$MH = RuntimeHelper.downcallHandle(
        "nc_put_var1_uint",
        constants$28.nc_put_var1_uint$FUNC
    );
    static final FunctionDescriptor nc_get_var1_uint$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var1_uint$MH = RuntimeHelper.downcallHandle(
        "nc_get_var1_uint",
        constants$28.nc_get_var1_uint$FUNC
    );
    static final FunctionDescriptor nc_put_var1_longlong$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var1_longlong$MH = RuntimeHelper.downcallHandle(
        "nc_put_var1_longlong",
        constants$28.nc_put_var1_longlong$FUNC
    );
    static final FunctionDescriptor nc_get_var1_longlong$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var1_longlong$MH = RuntimeHelper.downcallHandle(
        "nc_get_var1_longlong",
        constants$28.nc_get_var1_longlong$FUNC
    );
    static final FunctionDescriptor nc_put_var1_ulonglong$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var1_ulonglong$MH = RuntimeHelper.downcallHandle(
        "nc_put_var1_ulonglong",
        constants$28.nc_put_var1_ulonglong$FUNC
    );
}


