// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$54 {

    static final FunctionDescriptor ncdimid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ncdimid$MH = RuntimeHelper.downcallHandle(
        "ncdimid",
        constants$54.ncdimid$FUNC
    );
    static final FunctionDescriptor ncdiminq$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ncdiminq$MH = RuntimeHelper.downcallHandle(
        "ncdiminq",
        constants$54.ncdiminq$FUNC
    );
    static final FunctionDescriptor ncdimrename$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ncdimrename$MH = RuntimeHelper.downcallHandle(
        "ncdimrename",
        constants$54.ncdimrename$FUNC
    );
    static final FunctionDescriptor ncattput$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ncattput$MH = RuntimeHelper.downcallHandle(
        "ncattput",
        constants$54.ncattput$FUNC
    );
    static final FunctionDescriptor ncattinq$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ncattinq$MH = RuntimeHelper.downcallHandle(
        "ncattinq",
        constants$54.ncattinq$FUNC
    );
    static final FunctionDescriptor ncattget$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ncattget$MH = RuntimeHelper.downcallHandle(
        "ncattget",
        constants$54.ncattget$FUNC
    );
}


