// Generated by jextract

package com.sunya.netchdf.netcdfClib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$16 {

    static final FunctionDescriptor nc_close$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle nc_close$MH = RuntimeHelper.downcallHandle(
        "nc_close",
        constants$16.nc_close$FUNC
    );
    static final FunctionDescriptor nc_inq$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq$MH = RuntimeHelper.downcallHandle(
        "nc_inq",
        constants$16.nc_inq$FUNC
    );
    static final FunctionDescriptor nc_inq_ndims$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_ndims$MH = RuntimeHelper.downcallHandle(
        "nc_inq_ndims",
        constants$16.nc_inq_ndims$FUNC
    );
    static final FunctionDescriptor nc_inq_nvars$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_nvars$MH = RuntimeHelper.downcallHandle(
        "nc_inq_nvars",
        constants$16.nc_inq_nvars$FUNC
    );
    static final FunctionDescriptor nc_inq_natts$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_natts$MH = RuntimeHelper.downcallHandle(
        "nc_inq_natts",
        constants$16.nc_inq_natts$FUNC
    );
    static final FunctionDescriptor nc_inq_unlimdim$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_unlimdim$MH = RuntimeHelper.downcallHandle(
        "nc_inq_unlimdim",
        constants$16.nc_inq_unlimdim$FUNC
    );
}


