// Generated by jextract

package com.sunya.netchdf.netcdf4.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$9 {

    static final FunctionDescriptor nc_inq_enum_ident$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_enum_ident$MH = RuntimeHelper.downcallHandle(
        "nc_inq_enum_ident",
        constants$9.nc_inq_enum_ident$FUNC
    );
    static final FunctionDescriptor nc_def_opaque$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_def_opaque$MH = RuntimeHelper.downcallHandle(
        "nc_def_opaque",
        constants$9.nc_def_opaque$FUNC
    );
    static final FunctionDescriptor nc_inq_opaque$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_opaque$MH = RuntimeHelper.downcallHandle(
        "nc_inq_opaque",
        constants$9.nc_inq_opaque$FUNC
    );
    static final FunctionDescriptor nc_put_var$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var$MH = RuntimeHelper.downcallHandle(
        "nc_put_var",
        constants$9.nc_put_var$FUNC
    );
    static final FunctionDescriptor nc_get_var$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var$MH = RuntimeHelper.downcallHandle(
        "nc_get_var",
        constants$9.nc_get_var$FUNC
    );
    static final FunctionDescriptor nc_put_var1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var1$MH = RuntimeHelper.downcallHandle(
        "nc_put_var1",
        constants$9.nc_put_var1$FUNC
    );
}


