// Generated by jextract

package com.sunya.netchdf.netcdf4.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$38 {

    static final FunctionDescriptor nc_get_vars_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_vars_string$MH = RuntimeHelper.downcallHandle(
        "nc_get_vars_string",
        constants$38.nc_get_vars_string$FUNC
    );
    static final FunctionDescriptor nc_put_varm_text$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_varm_text$MH = RuntimeHelper.downcallHandle(
        "nc_put_varm_text",
        constants$38.nc_put_varm_text$FUNC
    );
    static final FunctionDescriptor nc_get_varm_text$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_varm_text$MH = RuntimeHelper.downcallHandle(
        "nc_get_varm_text",
        constants$38.nc_get_varm_text$FUNC
    );
    static final FunctionDescriptor nc_put_varm_uchar$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_varm_uchar$MH = RuntimeHelper.downcallHandle(
        "nc_put_varm_uchar",
        constants$38.nc_put_varm_uchar$FUNC
    );
    static final FunctionDescriptor nc_get_varm_uchar$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_varm_uchar$MH = RuntimeHelper.downcallHandle(
        "nc_get_varm_uchar",
        constants$38.nc_get_varm_uchar$FUNC
    );
    static final FunctionDescriptor nc_put_varm_schar$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_varm_schar$MH = RuntimeHelper.downcallHandle(
        "nc_put_varm_schar",
        constants$38.nc_put_varm_schar$FUNC
    );
}


