// Generated by jextract

package com.sunya.netchdf.netcdf4.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$17 {

    static final FunctionDescriptor nc_inq_dimid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_dimid$MH = RuntimeHelper.downcallHandle(
        "nc_inq_dimid",
        constants$17.nc_inq_dimid$FUNC
    );
    static final FunctionDescriptor nc_inq_dim$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_dim$MH = RuntimeHelper.downcallHandle(
        "nc_inq_dim",
        constants$17.nc_inq_dim$FUNC
    );
    static final FunctionDescriptor nc_inq_dimname$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_dimname$MH = RuntimeHelper.downcallHandle(
        "nc_inq_dimname",
        constants$17.nc_inq_dimname$FUNC
    );
    static final FunctionDescriptor nc_inq_dimlen$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_dimlen$MH = RuntimeHelper.downcallHandle(
        "nc_inq_dimlen",
        constants$17.nc_inq_dimlen$FUNC
    );
    static final FunctionDescriptor nc_rename_dim$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_rename_dim$MH = RuntimeHelper.downcallHandle(
        "nc_rename_dim",
        constants$17.nc_rename_dim$FUNC
    );
    static final FunctionDescriptor nc_inq_att$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_att$MH = RuntimeHelper.downcallHandle(
        "nc_inq_att",
        constants$17.nc_inq_att$FUNC
    );
}


