// Generated by jextract

package com.sunya.netchdf.netcdf4.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$27 {

    static final FunctionDescriptor nc_get_var1_long$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var1_long$MH = RuntimeHelper.downcallHandle(
        "nc_get_var1_long",
        constants$27.nc_get_var1_long$FUNC
    );
    static final FunctionDescriptor nc_put_var1_float$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var1_float$MH = RuntimeHelper.downcallHandle(
        "nc_put_var1_float",
        constants$27.nc_put_var1_float$FUNC
    );
    static final FunctionDescriptor nc_get_var1_float$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var1_float$MH = RuntimeHelper.downcallHandle(
        "nc_get_var1_float",
        constants$27.nc_get_var1_float$FUNC
    );
    static final FunctionDescriptor nc_put_var1_double$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var1_double$MH = RuntimeHelper.downcallHandle(
        "nc_put_var1_double",
        constants$27.nc_put_var1_double$FUNC
    );
    static final FunctionDescriptor nc_get_var1_double$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var1_double$MH = RuntimeHelper.downcallHandle(
        "nc_get_var1_double",
        constants$27.nc_get_var1_double$FUNC
    );
    static final FunctionDescriptor nc_put_var1_ushort$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var1_ushort$MH = RuntimeHelper.downcallHandle(
        "nc_put_var1_ushort",
        constants$27.nc_put_var1_ushort$FUNC
    );
}


