// Generated by jextract

package com.sunya.netchdf.netcdf4.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$43 {

    static final FunctionDescriptor nc_get_var_uchar$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var_uchar$MH = RuntimeHelper.downcallHandle(
        "nc_get_var_uchar",
        constants$43.nc_get_var_uchar$FUNC
    );
    static final FunctionDescriptor nc_put_var_schar$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var_schar$MH = RuntimeHelper.downcallHandle(
        "nc_put_var_schar",
        constants$43.nc_put_var_schar$FUNC
    );
    static final FunctionDescriptor nc_get_var_schar$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var_schar$MH = RuntimeHelper.downcallHandle(
        "nc_get_var_schar",
        constants$43.nc_get_var_schar$FUNC
    );
    static final FunctionDescriptor nc_put_var_short$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var_short$MH = RuntimeHelper.downcallHandle(
        "nc_put_var_short",
        constants$43.nc_put_var_short$FUNC
    );
    static final FunctionDescriptor nc_get_var_short$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_var_short$MH = RuntimeHelper.downcallHandle(
        "nc_get_var_short",
        constants$43.nc_get_var_short$FUNC
    );
    static final FunctionDescriptor nc_put_var_int$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_var_int$MH = RuntimeHelper.downcallHandle(
        "nc_put_var_int",
        constants$43.nc_put_var_int$FUNC
    );
}


