// Generated by jextract

package com.sunya.netchdf.netcdf4.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$36 {

    static final FunctionDescriptor nc_get_vars_float$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_vars_float$MH = RuntimeHelper.downcallHandle(
        "nc_get_vars_float",
        constants$36.nc_get_vars_float$FUNC
    );
    static final FunctionDescriptor nc_put_vars_double$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_vars_double$MH = RuntimeHelper.downcallHandle(
        "nc_put_vars_double",
        constants$36.nc_put_vars_double$FUNC
    );
    static final FunctionDescriptor nc_get_vars_double$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_vars_double$MH = RuntimeHelper.downcallHandle(
        "nc_get_vars_double",
        constants$36.nc_get_vars_double$FUNC
    );
    static final FunctionDescriptor nc_put_vars_ushort$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_vars_ushort$MH = RuntimeHelper.downcallHandle(
        "nc_put_vars_ushort",
        constants$36.nc_put_vars_ushort$FUNC
    );
    static final FunctionDescriptor nc_get_vars_ushort$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_vars_ushort$MH = RuntimeHelper.downcallHandle(
        "nc_get_vars_ushort",
        constants$36.nc_get_vars_ushort$FUNC
    );
    static final FunctionDescriptor nc_put_vars_uint$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_vars_uint$MH = RuntimeHelper.downcallHandle(
        "nc_put_vars_uint",
        constants$36.nc_put_vars_uint$FUNC
    );
}


