// Generated by jextract

package com.sunya.netchdf.netcdf4.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$2 {

    static final FunctionDescriptor nc_inq_grpname$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_grpname$MH = RuntimeHelper.downcallHandle(
        "nc_inq_grpname",
        constants$2.nc_inq_grpname$FUNC
    );
    static final FunctionDescriptor nc_inq_grpname_full$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_grpname_full$MH = RuntimeHelper.downcallHandle(
        "nc_inq_grpname_full",
        constants$2.nc_inq_grpname_full$FUNC
    );
    static final FunctionDescriptor nc_inq_grpname_len$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_grpname_len$MH = RuntimeHelper.downcallHandle(
        "nc_inq_grpname_len",
        constants$2.nc_inq_grpname_len$FUNC
    );
    static final FunctionDescriptor nc_inq_grp_parent$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_grp_parent$MH = RuntimeHelper.downcallHandle(
        "nc_inq_grp_parent",
        constants$2.nc_inq_grp_parent$FUNC
    );
    static final FunctionDescriptor nc_inq_grp_ncid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_grp_ncid$MH = RuntimeHelper.downcallHandle(
        "nc_inq_grp_ncid",
        constants$2.nc_inq_grp_ncid$FUNC
    );
    static final FunctionDescriptor nc_inq_grp_full_ncid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_inq_grp_full_ncid$MH = RuntimeHelper.downcallHandle(
        "nc_inq_grp_full_ncid",
        constants$2.nc_inq_grp_full_ncid$FUNC
    );
}


