// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$84 {

    static final  OfLong H5E_CANTCOMPUTE_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTCOMPUTE_g$VH = constants$84.H5E_CANTCOMPUTE_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTCOMPUTE_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTCOMPUTE_g", constants$84.H5E_CANTCOMPUTE_g$LAYOUT);
    static final  OfLong H5E_CANTEXTEND_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTEXTEND_g$VH = constants$84.H5E_CANTEXTEND_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTEXTEND_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTEXTEND_g", constants$84.H5E_CANTEXTEND_g$LAYOUT);
    static final  OfLong H5E_CANTATTACH_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTATTACH_g$VH = constants$84.H5E_CANTATTACH_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTATTACH_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTATTACH_g", constants$84.H5E_CANTATTACH_g$LAYOUT);
    static final  OfLong H5E_CANTUPDATE_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTUPDATE_g$VH = constants$84.H5E_CANTUPDATE_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTUPDATE_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTUPDATE_g", constants$84.H5E_CANTUPDATE_g$LAYOUT);
    static final  OfLong H5E_CANTOPERATE_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTOPERATE_g$VH = constants$84.H5E_CANTOPERATE_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTOPERATE_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTOPERATE_g", constants$84.H5E_CANTOPERATE_g$LAYOUT);
    static final  OfLong H5E_CANTINIT_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTINIT_g$VH = constants$84.H5E_CANTINIT_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTINIT_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTINIT_g", constants$84.H5E_CANTINIT_g$LAYOUT);
}


