// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$46 {

    static final FunctionDescriptor H5Oare_mdc_flushes_disabled$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Oare_mdc_flushes_disabled$MH = RuntimeHelper.downcallHandle(
        "H5Oare_mdc_flushes_disabled",
        constants$46.H5Oare_mdc_flushes_disabled$FUNC
    );
    static final FunctionDescriptor H5Oget_info$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Oget_info$MH = RuntimeHelper.downcallHandle(
        "H5Oget_info",
        constants$46.H5Oget_info$FUNC
    );
    static final FunctionDescriptor H5Oget_info_by_name$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Oget_info_by_name$MH = RuntimeHelper.downcallHandle(
        "H5Oget_info_by_name",
        constants$46.H5Oget_info_by_name$FUNC
    );
    static final FunctionDescriptor H5Oget_info_by_idx$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Oget_info_by_idx$MH = RuntimeHelper.downcallHandle(
        "H5Oget_info_by_idx",
        constants$46.H5Oget_info_by_idx$FUNC
    );
    static final FunctionDescriptor H5Ovisit$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Ovisit$MH = RuntimeHelper.downcallHandle(
        "H5Ovisit",
        constants$46.H5Ovisit$FUNC
    );
    static final FunctionDescriptor H5Ovisit_by_name$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Ovisit_by_name$MH = RuntimeHelper.downcallHandle(
        "H5Ovisit_by_name",
        constants$46.H5Ovisit_by_name$FUNC
    );
}


