// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$177 {

    static final FunctionDescriptor H5Sselect_hyperslab$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Sselect_hyperslab$MH = RuntimeHelper.downcallHandle(
        "H5Sselect_hyperslab",
        constants$177.H5Sselect_hyperslab$FUNC
    );
    static final FunctionDescriptor H5Scombine_hyperslab$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Scombine_hyperslab$MH = RuntimeHelper.downcallHandle(
        "H5Scombine_hyperslab",
        constants$177.H5Scombine_hyperslab$FUNC
    );
    static final FunctionDescriptor H5Smodify_select$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Smodify_select$MH = RuntimeHelper.downcallHandle(
        "H5Smodify_select",
        constants$177.H5Smodify_select$FUNC
    );
    static final FunctionDescriptor H5Scombine_select$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Scombine_select$MH = RuntimeHelper.downcallHandle(
        "H5Scombine_select",
        constants$177.H5Scombine_select$FUNC
    );
    static final FunctionDescriptor H5Sis_regular_hyperslab$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Sis_regular_hyperslab$MH = RuntimeHelper.downcallHandle(
        "H5Sis_regular_hyperslab",
        constants$177.H5Sis_regular_hyperslab$FUNC
    );
    static final FunctionDescriptor H5Sget_regular_hyperslab$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Sget_regular_hyperslab$MH = RuntimeHelper.downcallHandle(
        "H5Sget_regular_hyperslab",
        constants$177.H5Sget_regular_hyperslab$FUNC
    );
}


