// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$102 {

    static final  OfLong H5E_CANTDECODE_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTDECODE_g$VH = constants$102.H5E_CANTDECODE_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTDECODE_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTDECODE_g", constants$102.H5E_CANTDECODE_g$LAYOUT);
    static final  OfLong H5E_CANTSPLIT_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTSPLIT_g$VH = constants$102.H5E_CANTSPLIT_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTSPLIT_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTSPLIT_g", constants$102.H5E_CANTSPLIT_g$LAYOUT);
    static final  OfLong H5E_CANTREDISTRIBUTE_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTREDISTRIBUTE_g$VH = constants$102.H5E_CANTREDISTRIBUTE_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTREDISTRIBUTE_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTREDISTRIBUTE_g", constants$102.H5E_CANTREDISTRIBUTE_g$LAYOUT);
    static final  OfLong H5E_CANTSWAP_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTSWAP_g$VH = constants$102.H5E_CANTSWAP_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTSWAP_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTSWAP_g", constants$102.H5E_CANTSWAP_g$LAYOUT);
    static final  OfLong H5E_CANTINSERT_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTINSERT_g$VH = constants$102.H5E_CANTINSERT_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTINSERT_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTINSERT_g", constants$102.H5E_CANTINSERT_g$LAYOUT);
    static final  OfLong H5E_CANTLIST_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTLIST_g$VH = constants$102.H5E_CANTLIST_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTLIST_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTLIST_g", constants$102.H5E_CANTLIST_g$LAYOUT);
}


