// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$119 {

    static final FunctionDescriptor H5FDwrite$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5FDwrite$MH = RuntimeHelper.downcallHandle(
        "H5FDwrite",
        constants$119.H5FDwrite$FUNC
    );
    static final FunctionDescriptor H5FDflush$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_BOOL$LAYOUT
    );
    static final MethodHandle H5FDflush$MH = RuntimeHelper.downcallHandle(
        "H5FDflush",
        constants$119.H5FDflush$FUNC
    );
    static final FunctionDescriptor H5FDtruncate$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_BOOL$LAYOUT
    );
    static final MethodHandle H5FDtruncate$MH = RuntimeHelper.downcallHandle(
        "H5FDtruncate",
        constants$119.H5FDtruncate$FUNC
    );
    static final FunctionDescriptor H5FDlock$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_BOOL$LAYOUT
    );
    static final MethodHandle H5FDlock$MH = RuntimeHelper.downcallHandle(
        "H5FDlock",
        constants$119.H5FDlock$FUNC
    );
    static final FunctionDescriptor H5FDunlock$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5FDunlock$MH = RuntimeHelper.downcallHandle(
        "H5FDunlock",
        constants$119.H5FDunlock$FUNC
    );
    static final FunctionDescriptor H5FDdriver_query$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5FDdriver_query$MH = RuntimeHelper.downcallHandle(
        "H5FDdriver_query",
        constants$119.H5FDdriver_query$FUNC
    );
}


