// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$3 {

    static final FunctionDescriptor H5set_free_list_limits$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5set_free_list_limits$MH = RuntimeHelper.downcallHandle(
        "H5set_free_list_limits",
        constants$3.H5set_free_list_limits$FUNC
    );
    static final FunctionDescriptor H5get_free_list_sizes$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5get_free_list_sizes$MH = RuntimeHelper.downcallHandle(
        "H5get_free_list_sizes",
        constants$3.H5get_free_list_sizes$FUNC
    );
    static final FunctionDescriptor H5get_alloc_stats$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5get_alloc_stats$MH = RuntimeHelper.downcallHandle(
        "H5get_alloc_stats",
        constants$3.H5get_alloc_stats$FUNC
    );
    static final FunctionDescriptor H5get_libversion$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5get_libversion$MH = RuntimeHelper.downcallHandle(
        "H5get_libversion",
        constants$3.H5get_libversion$FUNC
    );
    static final FunctionDescriptor H5check_version$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5check_version$MH = RuntimeHelper.downcallHandle(
        "H5check_version",
        constants$3.H5check_version$FUNC
    );
    static final FunctionDescriptor H5is_library_threadsafe$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5is_library_threadsafe$MH = RuntimeHelper.downcallHandle(
        "H5is_library_threadsafe",
        constants$3.H5is_library_threadsafe$FUNC
    );
}


