// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$97 {

    static final  OfLong H5E_LOGGING_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_LOGGING_g$VH = constants$97.H5E_LOGGING_g$LAYOUT.varHandle();
    static final MemorySegment H5E_LOGGING_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_LOGGING_g", constants$97.H5E_LOGGING_g$LAYOUT);
    static final  OfLong H5E_LOGFAIL_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_LOGFAIL_g$VH = constants$97.H5E_LOGFAIL_g$LAYOUT.varHandle();
    static final MemorySegment H5E_LOGFAIL_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_LOGFAIL_g", constants$97.H5E_LOGFAIL_g$LAYOUT);
    static final  OfLong H5E_CANTCORK_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTCORK_g$VH = constants$97.H5E_CANTCORK_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTCORK_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTCORK_g", constants$97.H5E_CANTCORK_g$LAYOUT);
    static final  OfLong H5E_CANTUNCORK_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTUNCORK_g$VH = constants$97.H5E_CANTUNCORK_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTUNCORK_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTUNCORK_g", constants$97.H5E_CANTUNCORK_g$LAYOUT);
    static final  OfLong H5E_TRAVERSE_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_TRAVERSE_g$VH = constants$97.H5E_TRAVERSE_g$LAYOUT.varHandle();
    static final MemorySegment H5E_TRAVERSE_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_TRAVERSE_g", constants$97.H5E_TRAVERSE_g$LAYOUT);
    static final  OfLong H5E_NLINKS_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_NLINKS_g$VH = constants$97.H5E_NLINKS_g$LAYOUT.varHandle();
    static final MemorySegment H5E_NLINKS_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_NLINKS_g", constants$97.H5E_NLINKS_g$LAYOUT);
}


