// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$92 {

    static final  OfLong H5E_BADATOM_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_BADATOM_g$VH = constants$92.H5E_BADATOM_g$LAYOUT.varHandle();
    static final MemorySegment H5E_BADATOM_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_BADATOM_g", constants$92.H5E_BADATOM_g$LAYOUT);
    static final  OfLong H5E_BADGROUP_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_BADGROUP_g$VH = constants$92.H5E_BADGROUP_g$LAYOUT.varHandle();
    static final MemorySegment H5E_BADGROUP_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_BADGROUP_g", constants$92.H5E_BADGROUP_g$LAYOUT);
    static final  OfLong H5E_CANTREGISTER_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTREGISTER_g$VH = constants$92.H5E_CANTREGISTER_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTREGISTER_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTREGISTER_g", constants$92.H5E_CANTREGISTER_g$LAYOUT);
    static final  OfLong H5E_CANTINC_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTINC_g$VH = constants$92.H5E_CANTINC_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTINC_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTINC_g", constants$92.H5E_CANTINC_g$LAYOUT);
    static final  OfLong H5E_CANTDEC_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTDEC_g$VH = constants$92.H5E_CANTDEC_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTDEC_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTDEC_g", constants$92.H5E_CANTDEC_g$LAYOUT);
    static final  OfLong H5E_NOIDS_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_NOIDS_g$VH = constants$92.H5E_NOIDS_g$LAYOUT.varHandle();
    static final MemorySegment H5E_NOIDS_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_NOIDS_g", constants$92.H5E_NOIDS_g$LAYOUT);
}


