// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$164 {

    static final FunctionDescriptor H5Pset_local_heap_size_hint$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Pset_local_heap_size_hint$MH = RuntimeHelper.downcallHandle(
        "H5Pset_local_heap_size_hint",
        constants$164.H5Pset_local_heap_size_hint$FUNC
    );
    static final FunctionDescriptor H5Pget_local_heap_size_hint$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_local_heap_size_hint$MH = RuntimeHelper.downcallHandle(
        "H5Pget_local_heap_size_hint",
        constants$164.H5Pget_local_heap_size_hint$FUNC
    );
    static final FunctionDescriptor H5Pset_link_phase_change$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Pset_link_phase_change$MH = RuntimeHelper.downcallHandle(
        "H5Pset_link_phase_change",
        constants$164.H5Pset_link_phase_change$FUNC
    );
    static final FunctionDescriptor H5Pget_link_phase_change$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_link_phase_change$MH = RuntimeHelper.downcallHandle(
        "H5Pget_link_phase_change",
        constants$164.H5Pget_link_phase_change$FUNC
    );
    static final FunctionDescriptor H5Pset_est_link_info$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Pset_est_link_info$MH = RuntimeHelper.downcallHandle(
        "H5Pset_est_link_info",
        constants$164.H5Pset_est_link_info$FUNC
    );
    static final FunctionDescriptor H5Pget_est_link_info$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_est_link_info$MH = RuntimeHelper.downcallHandle(
        "H5Pget_est_link_info",
        constants$164.H5Pget_est_link_info$FUNC
    );
}


