// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$33 {

    static final FunctionDescriptor H5Tset_inpad$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Tset_inpad$MH = RuntimeHelper.downcallHandle(
        "H5Tset_inpad",
        constants$33.H5Tset_inpad$FUNC
    );
    static final FunctionDescriptor H5Tset_cset$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Tset_cset$MH = RuntimeHelper.downcallHandle(
        "H5Tset_cset",
        constants$33.H5Tset_cset$FUNC
    );
    static final FunctionDescriptor H5Tset_strpad$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Tset_strpad$MH = RuntimeHelper.downcallHandle(
        "H5Tset_strpad",
        constants$33.H5Tset_strpad$FUNC
    );
    static final FunctionDescriptor H5Tregister$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Tregister$MH = RuntimeHelper.downcallHandle(
        "H5Tregister",
        constants$33.H5Tregister$FUNC
    );
    static final FunctionDescriptor H5Tunregister$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Tunregister$MH = RuntimeHelper.downcallHandle(
        "H5Tunregister",
        constants$33.H5Tunregister$FUNC
    );
    static final FunctionDescriptor H5Tfind$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Tfind$MH = RuntimeHelper.downcallHandle(
        "H5Tfind",
        constants$33.H5Tfind$FUNC
    );
}


