// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$26 {

    static final FunctionDescriptor H5Tenum_insert$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Tenum_insert$MH = RuntimeHelper.downcallHandle(
        "H5Tenum_insert",
        constants$26.H5Tenum_insert$FUNC
    );
    static final FunctionDescriptor H5Tenum_nameof$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Tenum_nameof$MH = RuntimeHelper.downcallHandle(
        "H5Tenum_nameof",
        constants$26.H5Tenum_nameof$FUNC
    );
    static final FunctionDescriptor H5Tenum_valueof$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Tenum_valueof$MH = RuntimeHelper.downcallHandle(
        "H5Tenum_valueof",
        constants$26.H5Tenum_valueof$FUNC
    );
    static final FunctionDescriptor H5Tvlen_create$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Tvlen_create$MH = RuntimeHelper.downcallHandle(
        "H5Tvlen_create",
        constants$26.H5Tvlen_create$FUNC
    );
    static final FunctionDescriptor H5Tarray_create2$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Tarray_create2$MH = RuntimeHelper.downcallHandle(
        "H5Tarray_create2",
        constants$26.H5Tarray_create2$FUNC
    );
    static final FunctionDescriptor H5Tget_array_ndims$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Tget_array_ndims$MH = RuntimeHelper.downcallHandle(
        "H5Tget_array_ndims",
        constants$26.H5Tget_array_ndims$FUNC
    );
}


