// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$144 {

    static final FunctionDescriptor H5Pset_sym_k$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Pset_sym_k$MH = RuntimeHelper.downcallHandle(
        "H5Pset_sym_k",
        constants$144.H5Pset_sym_k$FUNC
    );
    static final FunctionDescriptor H5Pget_sym_k$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_sym_k$MH = RuntimeHelper.downcallHandle(
        "H5Pget_sym_k",
        constants$144.H5Pget_sym_k$FUNC
    );
    static final FunctionDescriptor H5Pset_istore_k$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Pset_istore_k$MH = RuntimeHelper.downcallHandle(
        "H5Pset_istore_k",
        constants$144.H5Pset_istore_k$FUNC
    );
    static final FunctionDescriptor H5Pget_istore_k$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_istore_k$MH = RuntimeHelper.downcallHandle(
        "H5Pget_istore_k",
        constants$144.H5Pget_istore_k$FUNC
    );
    static final FunctionDescriptor H5Pset_shared_mesg_nindexes$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Pset_shared_mesg_nindexes$MH = RuntimeHelper.downcallHandle(
        "H5Pset_shared_mesg_nindexes",
        constants$144.H5Pset_shared_mesg_nindexes$FUNC
    );
    static final FunctionDescriptor H5Pget_shared_mesg_nindexes$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_shared_mesg_nindexes$MH = RuntimeHelper.downcallHandle(
        "H5Pget_shared_mesg_nindexes",
        constants$144.H5Pget_shared_mesg_nindexes$FUNC
    );
}


