// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$117 {

    static final FunctionDescriptor H5FDunregister$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5FDunregister$MH = RuntimeHelper.downcallHandle(
        "H5FDunregister",
        constants$117.H5FDunregister$FUNC
    );
    static final FunctionDescriptor H5FDopen$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5FDopen$MH = RuntimeHelper.downcallHandle(
        "H5FDopen",
        constants$117.H5FDopen$FUNC
    );
    static final FunctionDescriptor H5FDclose$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5FDclose$MH = RuntimeHelper.downcallHandle(
        "H5FDclose",
        constants$117.H5FDclose$FUNC
    );
    static final FunctionDescriptor H5FDcmp$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5FDcmp$MH = RuntimeHelper.downcallHandle(
        "H5FDcmp",
        constants$117.H5FDcmp$FUNC
    );
    static final FunctionDescriptor H5FDquery$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5FDquery$MH = RuntimeHelper.downcallHandle(
        "H5FDquery",
        constants$117.H5FDquery$FUNC
    );
    static final FunctionDescriptor H5FDalloc$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5FDalloc$MH = RuntimeHelper.downcallHandle(
        "H5FDalloc",
        constants$117.H5FDalloc$FUNC
    );
}


