// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$104 {

    static final FunctionDescriptor H5E_auto2_t$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5E_auto2_t$MH = RuntimeHelper.downcallHandle(
        constants$104.H5E_auto2_t$FUNC
    );
    static final FunctionDescriptor H5Eregister_class$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Eregister_class$MH = RuntimeHelper.downcallHandle(
        "H5Eregister_class",
        constants$104.H5Eregister_class$FUNC
    );
    static final FunctionDescriptor H5Eunregister_class$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Eunregister_class$MH = RuntimeHelper.downcallHandle(
        "H5Eunregister_class",
        constants$104.H5Eunregister_class$FUNC
    );
    static final FunctionDescriptor H5Eclose_msg$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Eclose_msg$MH = RuntimeHelper.downcallHandle(
        "H5Eclose_msg",
        constants$104.H5Eclose_msg$FUNC
    );
    static final FunctionDescriptor H5Ecreate_msg$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Ecreate_msg$MH = RuntimeHelper.downcallHandle(
        "H5Ecreate_msg",
        constants$104.H5Ecreate_msg$FUNC
    );
}


