// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$169 {

    static final FunctionDescriptor H5Pget_version$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_version$MH = RuntimeHelper.downcallHandle(
        "H5Pget_version",
        constants$169.H5Pget_version$FUNC
    );
    static final FunctionDescriptor H5Pset_file_space$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Pset_file_space$MH = RuntimeHelper.downcallHandle(
        "H5Pset_file_space",
        constants$169.H5Pset_file_space$FUNC
    );
    static final FunctionDescriptor H5Pget_file_space$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_file_space$MH = RuntimeHelper.downcallHandle(
        "H5Pget_file_space",
        constants$169.H5Pget_file_space$FUNC
    );
    static final FunctionDescriptor H5PLset_loading_state$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5PLset_loading_state$MH = RuntimeHelper.downcallHandle(
        "H5PLset_loading_state",
        constants$169.H5PLset_loading_state$FUNC
    );
    static final FunctionDescriptor H5PLget_loading_state$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5PLget_loading_state$MH = RuntimeHelper.downcallHandle(
        "H5PLget_loading_state",
        constants$169.H5PLget_loading_state$FUNC
    );
    static final FunctionDescriptor H5PLappend$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5PLappend$MH = RuntimeHelper.downcallHandle(
        "H5PLappend",
        constants$169.H5PLappend$FUNC
    );
}


