// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$168 {

    static final FunctionDescriptor H5Pset_mcdt_search_cb$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pset_mcdt_search_cb$MH = RuntimeHelper.downcallHandle(
        "H5Pset_mcdt_search_cb",
        constants$168.H5Pset_mcdt_search_cb$FUNC
    );
    static final FunctionDescriptor H5Pget_mcdt_search_cb$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_mcdt_search_cb$MH = RuntimeHelper.downcallHandle(
        "H5Pget_mcdt_search_cb",
        constants$168.H5Pget_mcdt_search_cb$FUNC
    );
    static final FunctionDescriptor H5Pregister1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pregister1$MH = RuntimeHelper.downcallHandle(
        "H5Pregister1",
        constants$168.H5Pregister1$FUNC
    );
    static final FunctionDescriptor H5Pinsert1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pinsert1$MH = RuntimeHelper.downcallHandle(
        "H5Pinsert1",
        constants$168.H5Pinsert1$FUNC
    );
    static final FunctionDescriptor H5Pget_filter1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_filter1$MH = RuntimeHelper.downcallHandle(
        "H5Pget_filter1",
        constants$168.H5Pget_filter1$FUNC
    );
    static final FunctionDescriptor H5Pget_filter_by_id1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_filter_by_id1$MH = RuntimeHelper.downcallHandle(
        "H5Pget_filter_by_id1",
        constants$168.H5Pget_filter_by_id1$FUNC
    );
}


