// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$159 {

    static final FunctionDescriptor H5Pget_chunk_cache$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_chunk_cache$MH = RuntimeHelper.downcallHandle(
        "H5Pget_chunk_cache",
        constants$159.H5Pget_chunk_cache$FUNC
    );
    static final FunctionDescriptor H5Pset_virtual_view$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Pset_virtual_view$MH = RuntimeHelper.downcallHandle(
        "H5Pset_virtual_view",
        constants$159.H5Pset_virtual_view$FUNC
    );
    static final FunctionDescriptor H5Pget_virtual_view$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_virtual_view$MH = RuntimeHelper.downcallHandle(
        "H5Pget_virtual_view",
        constants$159.H5Pget_virtual_view$FUNC
    );
    static final FunctionDescriptor H5Pset_virtual_printf_gap$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Pset_virtual_printf_gap$MH = RuntimeHelper.downcallHandle(
        "H5Pset_virtual_printf_gap",
        constants$159.H5Pset_virtual_printf_gap$FUNC
    );
    static final FunctionDescriptor H5Pget_virtual_printf_gap$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_virtual_printf_gap$MH = RuntimeHelper.downcallHandle(
        "H5Pget_virtual_printf_gap",
        constants$159.H5Pget_virtual_printf_gap$FUNC
    );
    static final FunctionDescriptor H5Pset_virtual_prefix$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pset_virtual_prefix$MH = RuntimeHelper.downcallHandle(
        "H5Pset_virtual_prefix",
        constants$159.H5Pset_virtual_prefix$FUNC
    );
}


