// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$20 {

    static final  OfLong H5T_NATIVE_UINT_FAST8_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_NATIVE_UINT_FAST8_g$VH = constants$20.H5T_NATIVE_UINT_FAST8_g$LAYOUT.varHandle();
    static final MemorySegment H5T_NATIVE_UINT_FAST8_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_NATIVE_UINT_FAST8_g", constants$20.H5T_NATIVE_UINT_FAST8_g$LAYOUT);
    static final  OfLong H5T_NATIVE_INT16_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_NATIVE_INT16_g$VH = constants$20.H5T_NATIVE_INT16_g$LAYOUT.varHandle();
    static final MemorySegment H5T_NATIVE_INT16_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_NATIVE_INT16_g", constants$20.H5T_NATIVE_INT16_g$LAYOUT);
    static final  OfLong H5T_NATIVE_UINT16_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_NATIVE_UINT16_g$VH = constants$20.H5T_NATIVE_UINT16_g$LAYOUT.varHandle();
    static final MemorySegment H5T_NATIVE_UINT16_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_NATIVE_UINT16_g", constants$20.H5T_NATIVE_UINT16_g$LAYOUT);
    static final  OfLong H5T_NATIVE_INT_LEAST16_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_NATIVE_INT_LEAST16_g$VH = constants$20.H5T_NATIVE_INT_LEAST16_g$LAYOUT.varHandle();
    static final MemorySegment H5T_NATIVE_INT_LEAST16_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_NATIVE_INT_LEAST16_g", constants$20.H5T_NATIVE_INT_LEAST16_g$LAYOUT);
    static final  OfLong H5T_NATIVE_UINT_LEAST16_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_NATIVE_UINT_LEAST16_g$VH = constants$20.H5T_NATIVE_UINT_LEAST16_g$LAYOUT.varHandle();
    static final MemorySegment H5T_NATIVE_UINT_LEAST16_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_NATIVE_UINT_LEAST16_g", constants$20.H5T_NATIVE_UINT_LEAST16_g$LAYOUT);
    static final  OfLong H5T_NATIVE_INT_FAST16_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_NATIVE_INT_FAST16_g$VH = constants$20.H5T_NATIVE_INT_FAST16_g$LAYOUT.varHandle();
    static final MemorySegment H5T_NATIVE_INT_FAST16_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_NATIVE_INT_FAST16_g", constants$20.H5T_NATIVE_INT_FAST16_g$LAYOUT);
}


