// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$7 {

    static final FunctionDescriptor H5Idestroy_type$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Idestroy_type$MH = RuntimeHelper.downcallHandle(
        "H5Idestroy_type",
        constants$7.H5Idestroy_type$FUNC
    );
    static final FunctionDescriptor H5Iinc_type_ref$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Iinc_type_ref$MH = RuntimeHelper.downcallHandle(
        "H5Iinc_type_ref",
        constants$7.H5Iinc_type_ref$FUNC
    );
    static final FunctionDescriptor H5Idec_type_ref$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Idec_type_ref$MH = RuntimeHelper.downcallHandle(
        "H5Idec_type_ref",
        constants$7.H5Idec_type_ref$FUNC
    );
    static final FunctionDescriptor H5Iget_type_ref$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Iget_type_ref$MH = RuntimeHelper.downcallHandle(
        "H5Iget_type_ref",
        constants$7.H5Iget_type_ref$FUNC
    );
    static final FunctionDescriptor H5Isearch$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Isearch$MH = RuntimeHelper.downcallHandle(
        "H5Isearch",
        constants$7.H5Isearch$FUNC
    );
    static final FunctionDescriptor H5Inmembers$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Inmembers$MH = RuntimeHelper.downcallHandle(
        "H5Inmembers",
        constants$7.H5Inmembers$FUNC
    );
}


