// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$29 {

    static final FunctionDescriptor H5Tget_fields$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Tget_fields$MH = RuntimeHelper.downcallHandle(
        "H5Tget_fields",
        constants$29.H5Tget_fields$FUNC
    );
    static final FunctionDescriptor H5Tget_ebias$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Tget_ebias$MH = RuntimeHelper.downcallHandle(
        "H5Tget_ebias",
        constants$29.H5Tget_ebias$FUNC
    );
    static final FunctionDescriptor H5Tget_norm$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Tget_norm$MH = RuntimeHelper.downcallHandle(
        "H5Tget_norm",
        constants$29.H5Tget_norm$FUNC
    );
    static final FunctionDescriptor H5Tget_inpad$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Tget_inpad$MH = RuntimeHelper.downcallHandle(
        "H5Tget_inpad",
        constants$29.H5Tget_inpad$FUNC
    );
    static final FunctionDescriptor H5Tget_strpad$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Tget_strpad$MH = RuntimeHelper.downcallHandle(
        "H5Tget_strpad",
        constants$29.H5Tget_strpad$FUNC
    );
    static final FunctionDescriptor H5Tget_nmembers$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Tget_nmembers$MH = RuntimeHelper.downcallHandle(
        "H5Tget_nmembers",
        constants$29.H5Tget_nmembers$FUNC
    );
}


