// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$141 {

    static final FunctionDescriptor H5Pget_attr_phase_change$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_attr_phase_change$MH = RuntimeHelper.downcallHandle(
        "H5Pget_attr_phase_change",
        constants$141.H5Pget_attr_phase_change$FUNC
    );
    static final FunctionDescriptor H5Pset_attr_creation_order$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Pset_attr_creation_order$MH = RuntimeHelper.downcallHandle(
        "H5Pset_attr_creation_order",
        constants$141.H5Pset_attr_creation_order$FUNC
    );
    static final FunctionDescriptor H5Pget_attr_creation_order$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_attr_creation_order$MH = RuntimeHelper.downcallHandle(
        "H5Pget_attr_creation_order",
        constants$141.H5Pget_attr_creation_order$FUNC
    );
    static final FunctionDescriptor H5Pset_obj_track_times$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_BOOL$LAYOUT
    );
    static final MethodHandle H5Pset_obj_track_times$MH = RuntimeHelper.downcallHandle(
        "H5Pset_obj_track_times",
        constants$141.H5Pset_obj_track_times$FUNC
    );
    static final FunctionDescriptor H5Pget_obj_track_times$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_obj_track_times$MH = RuntimeHelper.downcallHandle(
        "H5Pget_obj_track_times",
        constants$141.H5Pget_obj_track_times$FUNC
    );
    static final FunctionDescriptor H5Pmodify_filter$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pmodify_filter$MH = RuntimeHelper.downcallHandle(
        "H5Pmodify_filter",
        constants$141.H5Pmodify_filter$FUNC
    );
}


