// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$22 {

    static final  OfLong H5T_NATIVE_UINT_FAST32_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_NATIVE_UINT_FAST32_g$VH = constants$22.H5T_NATIVE_UINT_FAST32_g$LAYOUT.varHandle();
    static final MemorySegment H5T_NATIVE_UINT_FAST32_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_NATIVE_UINT_FAST32_g", constants$22.H5T_NATIVE_UINT_FAST32_g$LAYOUT);
    static final  OfLong H5T_NATIVE_INT64_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_NATIVE_INT64_g$VH = constants$22.H5T_NATIVE_INT64_g$LAYOUT.varHandle();
    static final MemorySegment H5T_NATIVE_INT64_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_NATIVE_INT64_g", constants$22.H5T_NATIVE_INT64_g$LAYOUT);
    static final  OfLong H5T_NATIVE_UINT64_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_NATIVE_UINT64_g$VH = constants$22.H5T_NATIVE_UINT64_g$LAYOUT.varHandle();
    static final MemorySegment H5T_NATIVE_UINT64_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_NATIVE_UINT64_g", constants$22.H5T_NATIVE_UINT64_g$LAYOUT);
    static final  OfLong H5T_NATIVE_INT_LEAST64_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_NATIVE_INT_LEAST64_g$VH = constants$22.H5T_NATIVE_INT_LEAST64_g$LAYOUT.varHandle();
    static final MemorySegment H5T_NATIVE_INT_LEAST64_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_NATIVE_INT_LEAST64_g", constants$22.H5T_NATIVE_INT_LEAST64_g$LAYOUT);
    static final  OfLong H5T_NATIVE_UINT_LEAST64_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_NATIVE_UINT_LEAST64_g$VH = constants$22.H5T_NATIVE_UINT_LEAST64_g$LAYOUT.varHandle();
    static final MemorySegment H5T_NATIVE_UINT_LEAST64_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_NATIVE_UINT_LEAST64_g", constants$22.H5T_NATIVE_UINT_LEAST64_g$LAYOUT);
    static final  OfLong H5T_NATIVE_INT_FAST64_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_NATIVE_INT_FAST64_g$VH = constants$22.H5T_NATIVE_INT_FAST64_g$LAYOUT.varHandle();
    static final MemorySegment H5T_NATIVE_INT_FAST64_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_NATIVE_INT_FAST64_g", constants$22.H5T_NATIVE_INT_FAST64_g$LAYOUT);
}


