// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$60 {

    static final FunctionDescriptor H5Dget_chunk_index_type$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Dget_chunk_index_type$MH = RuntimeHelper.downcallHandle(
        "H5Dget_chunk_index_type",
        constants$60.H5Dget_chunk_index_type$FUNC
    );
    static final FunctionDescriptor H5Dcreate1$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Dcreate1$MH = RuntimeHelper.downcallHandle(
        "H5Dcreate1",
        constants$60.H5Dcreate1$FUNC
    );
    static final FunctionDescriptor H5Dopen1$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Dopen1$MH = RuntimeHelper.downcallHandle(
        "H5Dopen1",
        constants$60.H5Dopen1$FUNC
    );
    static final FunctionDescriptor H5Dextend$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Dextend$MH = RuntimeHelper.downcallHandle(
        "H5Dextend",
        constants$60.H5Dextend$FUNC
    );
    static final  OfAddress stdin$LAYOUT = Constants$root.C_POINTER$LAYOUT;
    static final VarHandle stdin$VH = constants$60.stdin$LAYOUT.varHandle();
    static final MemorySegment stdin$SEGMENT = RuntimeHelper.lookupGlobalVariable("stdin", constants$60.stdin$LAYOUT);
    static final  OfAddress stdout$LAYOUT = Constants$root.C_POINTER$LAYOUT;
    static final VarHandle stdout$VH = constants$60.stdout$LAYOUT.varHandle();
    static final MemorySegment stdout$SEGMENT = RuntimeHelper.lookupGlobalVariable("stdout", constants$60.stdout$LAYOUT);
}


