// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$14 {

    static final  OfLong H5T_UNIX_D32BE_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_UNIX_D32BE_g$VH = constants$14.H5T_UNIX_D32BE_g$LAYOUT.varHandle();
    static final MemorySegment H5T_UNIX_D32BE_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_UNIX_D32BE_g", constants$14.H5T_UNIX_D32BE_g$LAYOUT);
    static final  OfLong H5T_UNIX_D32LE_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_UNIX_D32LE_g$VH = constants$14.H5T_UNIX_D32LE_g$LAYOUT.varHandle();
    static final MemorySegment H5T_UNIX_D32LE_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_UNIX_D32LE_g", constants$14.H5T_UNIX_D32LE_g$LAYOUT);
    static final  OfLong H5T_UNIX_D64BE_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_UNIX_D64BE_g$VH = constants$14.H5T_UNIX_D64BE_g$LAYOUT.varHandle();
    static final MemorySegment H5T_UNIX_D64BE_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_UNIX_D64BE_g", constants$14.H5T_UNIX_D64BE_g$LAYOUT);
    static final  OfLong H5T_UNIX_D64LE_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_UNIX_D64LE_g$VH = constants$14.H5T_UNIX_D64LE_g$LAYOUT.varHandle();
    static final MemorySegment H5T_UNIX_D64LE_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_UNIX_D64LE_g", constants$14.H5T_UNIX_D64LE_g$LAYOUT);
    static final  OfLong H5T_C_S1_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_C_S1_g$VH = constants$14.H5T_C_S1_g$LAYOUT.varHandle();
    static final MemorySegment H5T_C_S1_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_C_S1_g", constants$14.H5T_C_S1_g$LAYOUT);
    static final  OfLong H5T_FORTRAN_S1_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5T_FORTRAN_S1_g$VH = constants$14.H5T_FORTRAN_S1_g$LAYOUT.varHandle();
    static final MemorySegment H5T_FORTRAN_S1_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5T_FORTRAN_S1_g", constants$14.H5T_FORTRAN_S1_g$LAYOUT);
}


