// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$56 {

    static final FunctionDescriptor H5Dget_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Dget_type$MH = RuntimeHelper.downcallHandle(
        "H5Dget_type",
        constants$56.H5Dget_type$FUNC
    );
    static final FunctionDescriptor H5Dget_create_plist$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Dget_create_plist$MH = RuntimeHelper.downcallHandle(
        "H5Dget_create_plist",
        constants$56.H5Dget_create_plist$FUNC
    );
    static final FunctionDescriptor H5Dget_access_plist$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Dget_access_plist$MH = RuntimeHelper.downcallHandle(
        "H5Dget_access_plist",
        constants$56.H5Dget_access_plist$FUNC
    );
    static final FunctionDescriptor H5Dget_storage_size$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Dget_storage_size$MH = RuntimeHelper.downcallHandle(
        "H5Dget_storage_size",
        constants$56.H5Dget_storage_size$FUNC
    );
    static final FunctionDescriptor H5Dget_chunk_storage_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Dget_chunk_storage_size$MH = RuntimeHelper.downcallHandle(
        "H5Dget_chunk_storage_size",
        constants$56.H5Dget_chunk_storage_size$FUNC
    );
    static final FunctionDescriptor H5Dget_num_chunks$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Dget_num_chunks$MH = RuntimeHelper.downcallHandle(
        "H5Dget_num_chunks",
        constants$56.H5Dget_num_chunks$FUNC
    );
}


