// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$5 {

    static final FunctionDescriptor H5I_search_func_t$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5I_search_func_t$MH = RuntimeHelper.downcallHandle(
        constants$5.H5I_search_func_t$FUNC
    );
    static final FunctionDescriptor H5Iregister$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Iregister$MH = RuntimeHelper.downcallHandle(
        "H5Iregister",
        constants$5.H5Iregister$FUNC
    );
    static final FunctionDescriptor H5Iobject_verify$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Iobject_verify$MH = RuntimeHelper.downcallHandle(
        "H5Iobject_verify",
        constants$5.H5Iobject_verify$FUNC
    );
    static final FunctionDescriptor H5Iremove_verify$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5Iremove_verify$MH = RuntimeHelper.downcallHandle(
        "H5Iremove_verify",
        constants$5.H5Iremove_verify$FUNC
    );
    static final FunctionDescriptor H5Iget_type$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Iget_type$MH = RuntimeHelper.downcallHandle(
        "H5Iget_type",
        constants$5.H5Iget_type$FUNC
    );
    static final FunctionDescriptor H5Iget_file_id$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Iget_file_id$MH = RuntimeHelper.downcallHandle(
        "H5Iget_file_id",
        constants$5.H5Iget_file_id$FUNC
    );
}


