// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$132 {

    static final  OfLong H5P_CLS_FILE_ACCESS_ID_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5P_CLS_FILE_ACCESS_ID_g$VH = constants$132.H5P_CLS_FILE_ACCESS_ID_g$LAYOUT.varHandle();
    static final MemorySegment H5P_CLS_FILE_ACCESS_ID_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5P_CLS_FILE_ACCESS_ID_g", constants$132.H5P_CLS_FILE_ACCESS_ID_g$LAYOUT);
    static final  OfLong H5P_CLS_DATASET_CREATE_ID_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5P_CLS_DATASET_CREATE_ID_g$VH = constants$132.H5P_CLS_DATASET_CREATE_ID_g$LAYOUT.varHandle();
    static final MemorySegment H5P_CLS_DATASET_CREATE_ID_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5P_CLS_DATASET_CREATE_ID_g", constants$132.H5P_CLS_DATASET_CREATE_ID_g$LAYOUT);
    static final  OfLong H5P_CLS_DATASET_ACCESS_ID_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5P_CLS_DATASET_ACCESS_ID_g$VH = constants$132.H5P_CLS_DATASET_ACCESS_ID_g$LAYOUT.varHandle();
    static final MemorySegment H5P_CLS_DATASET_ACCESS_ID_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5P_CLS_DATASET_ACCESS_ID_g", constants$132.H5P_CLS_DATASET_ACCESS_ID_g$LAYOUT);
    static final  OfLong H5P_CLS_DATASET_XFER_ID_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5P_CLS_DATASET_XFER_ID_g$VH = constants$132.H5P_CLS_DATASET_XFER_ID_g$LAYOUT.varHandle();
    static final MemorySegment H5P_CLS_DATASET_XFER_ID_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5P_CLS_DATASET_XFER_ID_g", constants$132.H5P_CLS_DATASET_XFER_ID_g$LAYOUT);
    static final  OfLong H5P_CLS_FILE_MOUNT_ID_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5P_CLS_FILE_MOUNT_ID_g$VH = constants$132.H5P_CLS_FILE_MOUNT_ID_g$LAYOUT.varHandle();
    static final MemorySegment H5P_CLS_FILE_MOUNT_ID_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5P_CLS_FILE_MOUNT_ID_g", constants$132.H5P_CLS_FILE_MOUNT_ID_g$LAYOUT);
    static final  OfLong H5P_CLS_GROUP_CREATE_ID_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5P_CLS_GROUP_CREATE_ID_g$VH = constants$132.H5P_CLS_GROUP_CREATE_ID_g$LAYOUT.varHandle();
    static final MemorySegment H5P_CLS_GROUP_CREATE_ID_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5P_CLS_GROUP_CREATE_ID_g", constants$132.H5P_CLS_GROUP_CREATE_ID_g$LAYOUT);
}


