// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$120 {

    static final FunctionDescriptor H5Gcreate2$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Gcreate2$MH = RuntimeHelper.downcallHandle(
        "H5Gcreate2",
        constants$120.H5Gcreate2$FUNC
    );
    static final FunctionDescriptor H5Gcreate_anon$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Gcreate_anon$MH = RuntimeHelper.downcallHandle(
        "H5Gcreate_anon",
        constants$120.H5Gcreate_anon$FUNC
    );
    static final FunctionDescriptor H5Gopen2$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Gopen2$MH = RuntimeHelper.downcallHandle(
        "H5Gopen2",
        constants$120.H5Gopen2$FUNC
    );
    static final FunctionDescriptor H5Gget_create_plist$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Gget_create_plist$MH = RuntimeHelper.downcallHandle(
        "H5Gget_create_plist",
        constants$120.H5Gget_create_plist$FUNC
    );
    static final FunctionDescriptor H5Gget_info$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Gget_info$MH = RuntimeHelper.downcallHandle(
        "H5Gget_info",
        constants$120.H5Gget_info$FUNC
    );
    static final FunctionDescriptor H5Gget_info_by_name$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Gget_info_by_name$MH = RuntimeHelper.downcallHandle(
        "H5Gget_info_by_name",
        constants$120.H5Gget_info_by_name$FUNC
    );
}


