// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$118 {

    static final FunctionDescriptor H5FDfree$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5FDfree$MH = RuntimeHelper.downcallHandle(
        "H5FDfree",
        constants$118.H5FDfree$FUNC
    );
    static final FunctionDescriptor H5FDget_eoa$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5FDget_eoa$MH = RuntimeHelper.downcallHandle(
        "H5FDget_eoa",
        constants$118.H5FDget_eoa$FUNC
    );
    static final FunctionDescriptor H5FDset_eoa$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5FDset_eoa$MH = RuntimeHelper.downcallHandle(
        "H5FDset_eoa",
        constants$118.H5FDset_eoa$FUNC
    );
    static final FunctionDescriptor H5FDget_eof$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle H5FDget_eof$MH = RuntimeHelper.downcallHandle(
        "H5FDget_eof",
        constants$118.H5FDget_eof$FUNC
    );
    static final FunctionDescriptor H5FDget_vfd_handle$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5FDget_vfd_handle$MH = RuntimeHelper.downcallHandle(
        "H5FDget_vfd_handle",
        constants$118.H5FDget_vfd_handle$FUNC
    );
    static final FunctionDescriptor H5FDread$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5FDread$MH = RuntimeHelper.downcallHandle(
        "H5FDread",
        constants$118.H5FDread$FUNC
    );
}


