// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$146 {

    static final FunctionDescriptor H5Pset_file_space_page_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Pset_file_space_page_size$MH = RuntimeHelper.downcallHandle(
        "H5Pset_file_space_page_size",
        constants$146.H5Pset_file_space_page_size$FUNC
    );
    static final FunctionDescriptor H5Pget_file_space_page_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_file_space_page_size$MH = RuntimeHelper.downcallHandle(
        "H5Pget_file_space_page_size",
        constants$146.H5Pget_file_space_page_size$FUNC
    );
    static final FunctionDescriptor H5Pset_alignment$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Pset_alignment$MH = RuntimeHelper.downcallHandle(
        "H5Pset_alignment",
        constants$146.H5Pset_alignment$FUNC
    );
    static final FunctionDescriptor H5Pget_alignment$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pget_alignment$MH = RuntimeHelper.downcallHandle(
        "H5Pget_alignment",
        constants$146.H5Pget_alignment$FUNC
    );
    static final FunctionDescriptor H5Pset_driver$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle H5Pset_driver$MH = RuntimeHelper.downcallHandle(
        "H5Pset_driver",
        constants$146.H5Pset_driver$FUNC
    );
    static final FunctionDescriptor H5Pget_driver$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle H5Pget_driver$MH = RuntimeHelper.downcallHandle(
        "H5Pget_driver",
        constants$146.H5Pget_driver$FUNC
    );
}


