// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$99 {

    static final  OfLong H5E_CANTGATHER_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTGATHER_g$VH = constants$99.H5E_CANTGATHER_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTGATHER_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTGATHER_g", constants$99.H5E_CANTGATHER_g$LAYOUT);
    static final  OfLong H5E_NO_INDEPENDENT_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_NO_INDEPENDENT_g$VH = constants$99.H5E_NO_INDEPENDENT_g$LAYOUT.varHandle();
    static final MemorySegment H5E_NO_INDEPENDENT_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_NO_INDEPENDENT_g", constants$99.H5E_NO_INDEPENDENT_g$LAYOUT);
    static final  OfLong H5E_CANTCLIP_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTCLIP_g$VH = constants$99.H5E_CANTCLIP_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTCLIP_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTCLIP_g", constants$99.H5E_CANTCLIP_g$LAYOUT);
    static final  OfLong H5E_CANTCOUNT_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTCOUNT_g$VH = constants$99.H5E_CANTCOUNT_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTCOUNT_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTCOUNT_g", constants$99.H5E_CANTCOUNT_g$LAYOUT);
    static final  OfLong H5E_CANTSELECT_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTSELECT_g$VH = constants$99.H5E_CANTSELECT_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTSELECT_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTSELECT_g", constants$99.H5E_CANTSELECT_g$LAYOUT);
    static final  OfLong H5E_CANTNEXT_g$LAYOUT = Constants$root.C_LONG_LONG$LAYOUT;
    static final VarHandle H5E_CANTNEXT_g$VH = constants$99.H5E_CANTNEXT_g$LAYOUT.varHandle();
    static final MemorySegment H5E_CANTNEXT_g$SEGMENT = RuntimeHelper.lookupGlobalVariable("H5E_CANTNEXT_g", constants$99.H5E_CANTNEXT_g$LAYOUT);
}


