// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface H5A_operator2_t {

    int apply(long location_id, java.lang.foreign.MemoryAddress attr_name, java.lang.foreign.MemoryAddress ainfo, java.lang.foreign.MemoryAddress op_data);
    static MemorySegment allocate(H5A_operator2_t fi, MemorySession session) {
        return RuntimeHelper.upcallStub(H5A_operator2_t.class, fi, constants$47.H5A_operator2_t$FUNC, session);
    }
    static H5A_operator2_t ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (long _location_id, java.lang.foreign.MemoryAddress _attr_name, java.lang.foreign.MemoryAddress _ainfo, java.lang.foreign.MemoryAddress _op_data) -> {
            try {
                return (int)constants$48.H5A_operator2_t$MH.invokeExact((Addressable)symbol, _location_id, (java.lang.foreign.Addressable)_attr_name, (java.lang.foreign.Addressable)_ainfo, (java.lang.foreign.Addressable)_op_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


