// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface H5F_flush_cb_t {

    int apply(long object_id, java.lang.foreign.MemoryAddress udata);
    static MemorySegment allocate(H5F_flush_cb_t fi, MemorySession session) {
        return RuntimeHelper.upcallStub(H5F_flush_cb_t.class, fi, constants$109.H5F_flush_cb_t$FUNC, session);
    }
    static H5F_flush_cb_t ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (long _object_id, java.lang.foreign.MemoryAddress _udata) -> {
            try {
                return (int)constants$109.H5F_flush_cb_t$MH.invokeExact((Addressable)symbol, _object_id, (java.lang.foreign.Addressable)_udata);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


