// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface H5O_iterate_t {

    int apply(long obj, java.lang.foreign.MemoryAddress name, java.lang.foreign.MemoryAddress info, java.lang.foreign.MemoryAddress op_data);
    static MemorySegment allocate(H5O_iterate_t fi, MemorySession session) {
        return RuntimeHelper.upcallStub(H5O_iterate_t.class, fi, constants$41.H5O_iterate_t$FUNC, session);
    }
    static H5O_iterate_t ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (long _obj, java.lang.foreign.MemoryAddress _name, java.lang.foreign.MemoryAddress _info, java.lang.foreign.MemoryAddress _op_data) -> {
            try {
                return (int)constants$41.H5O_iterate_t$MH.invokeExact((Addressable)symbol, _obj, (java.lang.foreign.Addressable)_name, (java.lang.foreign.Addressable)_info, (java.lang.foreign.Addressable)_op_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


