// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface H5O_mcdt_search_cb_t {

    int apply(java.lang.foreign.MemoryAddress op_data);
    static MemorySegment allocate(H5O_mcdt_search_cb_t fi, MemorySession session) {
        return RuntimeHelper.upcallStub(H5O_mcdt_search_cb_t.class, fi, constants$42.H5O_mcdt_search_cb_t$FUNC, session);
    }
    static H5O_mcdt_search_cb_t ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _op_data) -> {
            try {
                return (int)constants$42.H5O_mcdt_search_cb_t$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_op_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


