// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class H5O_stat_t {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("size"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("free"),
        Constants$root.C_INT$LAYOUT.withName("nmesgs"),
        Constants$root.C_INT$LAYOUT.withName("nchunks")
    ).withName("H5O_stat_t");
    public static MemoryLayout $LAYOUT() {
        return H5O_stat_t.$struct$LAYOUT;
    }
    static final VarHandle size$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("size"));
    public static VarHandle size$VH() {
        return H5O_stat_t.size$VH;
    }
    public static long size$get(MemorySegment seg) {
        return (long)H5O_stat_t.size$VH.get(seg);
    }
    public static void size$set( MemorySegment seg, long x) {
        H5O_stat_t.size$VH.set(seg, x);
    }
    public static long size$get(MemorySegment seg, long index) {
        return (long)H5O_stat_t.size$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void size$set(MemorySegment seg, long index, long x) {
        H5O_stat_t.size$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle free$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("free"));
    public static VarHandle free$VH() {
        return H5O_stat_t.free$VH;
    }
    public static long free$get(MemorySegment seg) {
        return (long)H5O_stat_t.free$VH.get(seg);
    }
    public static void free$set( MemorySegment seg, long x) {
        H5O_stat_t.free$VH.set(seg, x);
    }
    public static long free$get(MemorySegment seg, long index) {
        return (long)H5O_stat_t.free$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void free$set(MemorySegment seg, long index, long x) {
        H5O_stat_t.free$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle nmesgs$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("nmesgs"));
    public static VarHandle nmesgs$VH() {
        return H5O_stat_t.nmesgs$VH;
    }
    public static int nmesgs$get(MemorySegment seg) {
        return (int)H5O_stat_t.nmesgs$VH.get(seg);
    }
    public static void nmesgs$set( MemorySegment seg, int x) {
        H5O_stat_t.nmesgs$VH.set(seg, x);
    }
    public static int nmesgs$get(MemorySegment seg, long index) {
        return (int)H5O_stat_t.nmesgs$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void nmesgs$set(MemorySegment seg, long index, int x) {
        H5O_stat_t.nmesgs$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle nchunks$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("nchunks"));
    public static VarHandle nchunks$VH() {
        return H5O_stat_t.nchunks$VH;
    }
    public static int nchunks$get(MemorySegment seg) {
        return (int)H5O_stat_t.nchunks$VH.get(seg);
    }
    public static void nchunks$set( MemorySegment seg, int x) {
        H5O_stat_t.nchunks$VH.set(seg, x);
    }
    public static int nchunks$get(MemorySegment seg, long index) {
        return (int)H5O_stat_t.nchunks$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void nchunks$set(MemorySegment seg, long index, int x) {
        H5O_stat_t.nchunks$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


