// Generated by jextract

package com.sunya.netchdf.hdf5Clib.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface H5T_conv_t {

    int apply(long src_id, long dst_id, java.lang.foreign.MemoryAddress cdata, long nelmts, long buf_stride, long bkg_stride, java.lang.foreign.MemoryAddress buf, java.lang.foreign.MemoryAddress bkg, long dset_xfer_plist);
    static MemorySegment allocate(H5T_conv_t fi, MemorySession session) {
        return RuntimeHelper.upcallStub(H5T_conv_t.class, fi, constants$8.H5T_conv_t$FUNC, session);
    }
    static H5T_conv_t ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (long _src_id, long _dst_id, java.lang.foreign.MemoryAddress _cdata, long _nelmts, long _buf_stride, long _bkg_stride, java.lang.foreign.MemoryAddress _buf, java.lang.foreign.MemoryAddress _bkg, long _dset_xfer_plist) -> {
            try {
                return (int)constants$8.H5T_conv_t$MH.invokeExact((Addressable)symbol, _src_id, _dst_id, (java.lang.foreign.Addressable)_cdata, _nelmts, _buf_stride, _bkg_stride, (java.lang.foreign.Addressable)_buf, (java.lang.foreign.Addressable)_bkg, _dset_xfer_plist);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


