// Generated by jextract

package sunya.cdm.netcdf4.ffm;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$33 {

    static final FunctionDescriptor nc_get_vara_longlong$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_vara_longlong$MH = RuntimeHelper.downcallHandle(
        "nc_get_vara_longlong",
        constants$33.nc_get_vara_longlong$FUNC
    );
    static final FunctionDescriptor nc_put_vara_ulonglong$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_vara_ulonglong$MH = RuntimeHelper.downcallHandle(
        "nc_put_vara_ulonglong",
        constants$33.nc_put_vara_ulonglong$FUNC
    );
    static final FunctionDescriptor nc_get_vara_ulonglong$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_vara_ulonglong$MH = RuntimeHelper.downcallHandle(
        "nc_get_vara_ulonglong",
        constants$33.nc_get_vara_ulonglong$FUNC
    );
    static final FunctionDescriptor nc_put_vara_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_vara_string$MH = RuntimeHelper.downcallHandle(
        "nc_put_vara_string",
        constants$33.nc_put_vara_string$FUNC
    );
    static final FunctionDescriptor nc_get_vara_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_get_vara_string$MH = RuntimeHelper.downcallHandle(
        "nc_get_vara_string",
        constants$33.nc_get_vara_string$FUNC
    );
    static final FunctionDescriptor nc_put_vars_text$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nc_put_vars_text$MH = RuntimeHelper.downcallHandle(
        "nc_put_vars_text",
        constants$33.nc_put_vars_text$FUNC
    );
}


